### ISSUE TITLE
Application icon

### ISSUE THREAD

**Issue by special** [ricochet-im/ricochet#11]
Find someone to create a nice application icon. Minimum sizes of 256x256, 128x128, 32x32, and 16x16. 512x512 preferred.

Ideas welcome

**Comment by special** [comment]
![icon_128x128](https://cloud.githubusercontent.com/assets/80188/6361339/91b54100-bc3e-11e4-8cb5-912bb5f1cb07.png)

This design was sent to me privately; I didn't share it until now because I wasn't certain of the author's preference for licensing and attribution.

I've also unilaterally (rudely?) decided to start using it (PR #134). The upcoming release needs some more visual flair behind it, and this is a decent start.

I appreciate all the ideas here, and anyone looking for a place to use their artistic talents should stay in touch! OSS never has enough of it.

**Comment by obvio171** [comment]
Very compressible (into a flat favicon, for example) and seemingly unique. I like it. Anything trying to replicate the semantics of the name too closely would have a really hard time coming out as simple, so I guess it's indeed a decent start. Congrats to the author =)
