### ISSUE TITLE
implement the protocol in telepathy or (better) libpurple

### ISSUE THREAD

**Issue by mornfall** [ricochet-im/ricochet#110]
While I can see how creating a GUI program is tempting, I also suspect many many users won't want to run Yet Another Chat Program. I imagine most potential users will already be using IM in some form, and won't abandon ship immediately for a newcomer. Running multiple IM programs with different UI, different notification, separate contact lists, well, sucks. This is compounded by the fact that initially only very few people on our contact lists would be on ricochet/invisible.im. And don't forget about mobile phones... all in all, I would much prefer a libpurple plugin than a standalone GUI application (I normally use bitlbee for IM). Since telepathy can use libpurple plugins directly, that would also make it easy to integrate into my phone's messaging app, besides many people's desktop IM.

**Comment by special** [comment]
Closing this, since it's out of scope of the main project here. Still, anyone who is interested in making alternative implementations of the protocol should get in touch and read specs.

**Comment by rodneyrod** [comment]
As a person with little to no coding experience, I would love to see something like this go ahead.
It would mean I can easily integrate Ricochet with my existing libpurple messaging applications, and hopefully allow greater exposure to the protocol in general.

**Comment by graingert** [comment]
I think it would be better to implement an XMPP proxy for the protocol

**Comment by dllud** [comment]
Implementing a libpurple plugin brings other benefits besides the aforementioned de-duplication of IM programs:

- It avoids "reinventing the wheel". Right now, Ricochet's UI lacks many basic features people expect in an IM program. As a consequence, the issue tracker is already overloaded with [UI enhancement requests](https://github.com/ricochet-im/ricochet/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Aui%20). The majority of these are implemented in Pidgin or Empathy. It seems a waste of developer time to re-implement all this. Perhaps you could address @special 's concerns through a collaboration with Pidgin developers or by forcing safe defaults when the libpurple Ricochet plugin is activated for the first time.
- It allows usage of Pidgin's plugins on top of Ricochet protocol. Pidgin has a myriad of plugins, that range from silly games to Text-To-Speech. There are even secure message exchange protocols, such as OTR and the forthcoming OMEMO, that add security features absent in Ricochet (deniability and forward+future secrecy).

Perhaps @graingert 's XMPP proxy is the way to go...

**Comment by graingert** [comment]
@dllud now I think about it I worry that chat programs leak information anyway. Consider the relationship between firefox and tor in the Tor Browser Bundle

**Comment by timkuijsten** [comment]
I really like the fact that Ricochet does *not* use libpurple given libpurples track record[1][2][3].

[1] http://motherboard.vice.com/read/secure-messaging-might-not-be-so-secure-otr-libpurple
[2] https://web.nvd.nist.gov/view/vuln/search-results?query=libpurple&search_type=all&cves=on
[3] https://pidgin.im/news/security/

**Comment by graingert** [comment]
I suspect libpurple is bad news, but an XMPP or even IRC gateway could be pretty useful

**Comment by timkuijsten** [comment]
@graingert From an attack surface / "how hard is it to implement" perspective, I'm not a big fan of the XMPP protocol + the fact that it relies on XML.

**Comment by graingert** [comment]
Maybe an IRC gateway is best?

**Comment by timkuijsten** [comment]
@graingert haven't looked at it myself, but feel free ;) https://tools.ietf.org/html/rfc1459

**Comment by rodneyrod** [comment]
I think that making the libpurple shim but putting disclaimers all over the place about how it isn't officially supported would be the best way forward.

If you only provide the source and no binaries, that would go even further to preventing the uninitiated from accidentally installing that instead of the official client.
