### ISSUE TITLE
Integration of Tox.im core lib

### ISSUE THREAD

**Issue by HulaHoopWhonix** [ricochet-im/ricochet#116]
What if instead of building IM features from scratch, you could use a very advanced IM library like Tox core for all the expected functions like voip, file transfer, groupchat and mobile platform support (which would take care of https://github.com/ricochet-im/ricochet/issues/115)?

More information about Tox.im is summarized here:
https://www.whonix.org/wiki/VoIP#Tox

ricochet-im would be all about Tor-centric integration of these features by integrating hidden services authentication layer.

What do you think?

**Comment by hyiltiz** [comment]
OK, wikipedia didn't mention you were non-GPL and against copyleft. I would suggest you could add in those to wikipedia.

**Comment by hyiltiz** [comment]
But a BSD licence send so much against the idea of enforcing entice world into a privacy guaranteed state. But I will stop here since I am well aware of the BSD vs. GPL war.
