### ISSUE TITLE
Add UI messages about protocol incompatibility with contacts

### ISSUE THREAD

**Issue by special** [ricochet-im/ricochet#143]
We have a protocol negotiation step that lets us know when contacts don't speak a compatible version of the protocol, but right now that information is ignored.

In the case that we ever have to make breaking changes in the future, we should have messages that help the user understand this and know where to look in case they need to update. Not doing this has already caused us problems (see #140). Let's avoid having to do that again.

I'm thinking the individual contacts should go into some error state, and a message should be visible somewhere about why. Of course, we _can't_ assume that the error means there is an update available, or that the contact is the newer one.

**Comment by rburchell** [comment]
We have an indication of user connectivity, right? Why not have a: "Running outdated software" category, maybe with some text immediately underneath the banner explaining the situation?

**Comment by rburchell** [comment]
(text would ideally be greyed out so it's clear it's not an active UI element, and fairly to-the-point, similar to the message being pushed in #140)

**Comment by special** [comment]
Solved, I think, by #151.
