### ISSUE TITLE
Closing the main window should not quit the application on OS X.

### ISSUE THREAD

**Issue by SadieCat** [ricochet-im/ricochet#165]
When the main window closes the application exits. This is contrary to most chat applications on OS X which stay running in the background when the main window closes. It would be nice if Ricochet could follow this convention and stay running in the background when the main window is closed.

Vaguely related: #10

**Comment by schnauss** [comment]
I agree, and would go further- closing the window should not close the application in any OS- for example, Pidgin doesn't do that.

**Comment by nathanstretch** [comment]
Agreed.  I would like to have this running all the time on the off chance someone wants to send me an OTR message.  If they have to send me an email or unencrypted IM to ask me to turn it on, it kind of defeats the main advantage this has over other OTR clients.
