### ISSUE TITLE
Keyboard shortcuts for closing windows

### ISSUE THREAD

**Issue by kartoch** [ricochet-im/ricochet#169]
Using ricochet in tiling WM is a bit tricky, as they are no way to close main or configuration window using classical shortcuts. Is that possible to add a shortcuts to close such windows ?

**Comment by bigfighter** [comment]
That one tripped me up as well. If you happen to be using i3, try Shift+Mod+Q.

But generally speaking, I think it's a bad idea for applications to be put in charge of the window manager's job. Basically, you're describing an issue with the window manager, not with the application.

Having said that, putting the traditional OK/Cancel/Apply buttons on the settings dialog would not be a bad idea.

**Comment by special** [comment]
We should be closing windows on the OS hotkey (Alt+F4, or cmd+W on mac). That's a bug. Would that fix be enough of a solution, or is there something else worth changing?

OK/Cancel/Apply on the settings dialog would require changing everything to not immediate-apply, and that is a mess I don't like.
