### ISSUE TITLE
Setting for language choice

### ISSUE THREAD

**Issue by rawtaz** [ricochet-im/ricochet#172]
A friend just asked me "How can I change the language of the application?" (he's running OS X).

While there are ways to change the language of an application in OS X, it's not straight forward, and as it's pretty common to have an option for language in an application's settings, perhaps it would be a good idea to have in Ricochet too? Use case wise it might be less common, but I do know a bunch of people (including myself) that actually do prefer other languages than the general one in the system, for specific applications.

Would it be a lot of work to implement?

**Comment by special** [comment]
I think this is worth doing. It's not hard - add configuration UI, check the config before using the system default. The only slightly tricky part is building the list of languages.

Ideally, that could be done by looking at the contents of the `/lang` resource and using `QLocale::nativeLanguageName` to get the list. Then we wouldn't have to worry about keeping it up to date.
