### ISSUE TITLE
[qt problems] ricochet doesn't seem to start for me

### ISSUE THREAD

**Issue by 4DA** [ricochet-im/ricochet#173]
./ricochet
QQmlApplicationEngine failed to load component
qrc:/ui/main.qml:9 Type MainWindow unavailable
qrc:/ui/MainWindow.qml:68 Type ContactList unavailable
qrc:/ui/ContactList.qml:97 Type ContactListDelegate unavailable
qrc:/ui/ContactListDelegate.qml:54 Type ContactActions unavailable
qrc:/ui/ContactActions.qml:3 module "QtQuick.Dialogs" is not installed

i use debian testing with following relevant packages:
qt5-default: 5.3.2+dfsg-4+b1
qt5-qmake: 5.3.2+dfsg-4+b1
qtbase5-dev:  5.3.2+dfsg-4+b1
qtbase5-dev-tools:  5.3.2+dfsg-4+b1
qtdeclarative5-dev: 5.3.2-4
qttools5-dev-tools: 5.3.2-3

**Comment by rburchell** [comment]
You're missing a package. The hint is in the final error:

**Comment by special** [comment]
The currently known list of requirements on debian is in [BUILDING.md](https://github.com/ricochet-im/ricochet/blob/master/BUILDING.md):

```
apt-get install build-essential libssl-dev pkg-config libprotobuf-dev protobuf-compiler
apt-get install qt5-qmake qt5-default qtbase5-dev qttools5-dev-tools 
apt-get install qtdeclarative5-dev qtdeclarative5-controls-plugin
apt-get install tor # or build your own
```

If those don't work for you, can you find which package does and let us know?

**Comment by 4DA** [comment]
It does work indeed. Thx, guys.

On Sat, Apr 18, 2015 at 9:02 PM, John Brooks <notifications@github.com>
wrote:

> The currently known list of requirements on debian is in BUILDING.md
> <https://github.com/ricochet-im/ricochet/blob/master/BUILDING.md>:
>
> apt-get install build-essential libssl-dev pkg-config libprotobuf-dev protobuf-compiler
> apt-get install qt5-qmake qt5-default qtbase5-dev qttools5-dev-tools
> apt-get install qtdeclarative5-dev qtdeclarative5-controls-plugin
> apt-get install tor # or build your own
>
> If those don't work for you, can you find which package does and let us
> know?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ricochet-im/ricochet/issues/173#issuecomment-94187964>
> .
>



-- 
With best regards,
Dmitry
