### ISSUE TITLE
Links have confusing Copy behaviour

### ISSUE THREAD

**Issue by gabedwrds** [ricochet-im/ricochet#179]
The context menu for a link in chat has three options: Copy Link, Open with Browser, and Copy, the last one being non-specific to links. It copies selected text, or the entire message if nothing is selected.

If I brought up the context menu by *right*-clicking a link, "Copy" will copy the entire message. This makes sense, if I'm going to have multiple options for what to copy.

If I brought up the context menu by *left*-clicking a link, "Copy" will copy only the link, just like "Copy Link" (presumably it's selected implicitly somehow when activated). This is inconsistent and makes much less sense.

**Comment by special** [comment]
Neat. Thanks for the attention to detail.

I think the options here are:

 * Don't show "Copy" on a link - it's slightly ambiguous, and probably not what was intended
 * Fix "Copy" on left click to behave like it does for right click (copying all text)

I'm not sure which of these I prefer yet. On a vaguely related note, you don't get the link options if you click slightly above or below the link (but still within the bubble). That's slightly annoying.
