### ISSUE TITLE
Opening link crashes Windows client

### ISSUE THREAD

**Issue by sergeevabc** [ricochet-im/ricochet#180]
Let’s say Alice offers Bob to open a [link][1].
When it happens, Ricochet 1.1.0 on Bob’s machine crashes.
Windows crash report as follows:
```
  Problem Event Name:	APPCRASH
  Application Name:	ricochet.exe
  Application Version:	1.1.0.0
  Application Timestamp:	5526ff5b
  Fault Module Name:	Qt5Qml.dll
  Fault Module Version:	5.4.1.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	00141ba0
  OS Version:	6.1.7601.2.1.0.256.48
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789
```

[1]: https://github.com/ricochet-im/ricochet/issues/168

**Comment by special** [comment]
From a quick test, this appears to be Windows-specific, and it only happens when "Open links in default browser without prompting" is enabled (so, not by default).

**Comment by m1zg4rd** [comment]
This is maybe related to that bug, also two first context menu options disappear and standard "Copy" option for normal text is added to context menu for links, like in attached image. This occur for enabled alert window too.
![bug](https://cloud.githubusercontent.com/assets/10185310/8763635/4a55ae64-2da7-11e5-9d5f-18fdf7aa3072.png)

**Comment by special** [comment]
Can't reproduce the crash with Qt 5.5. If the menu text problem still appears with 1.1.1, it should go in a new bug. I'm hoping it's solved as well.
