### ISSUE TITLE
building on debian jessie - translations are not compiled with lrelease

### ISSUE THREAD

**Issue by esme-does-code** [ricochet-im/ricochet#184]
following the steps in BUILDING.md, qmake gives you a load of errors about missing files (translation_*.qm).

workaround: build like this
$ lrelease ricochet.pro
$ qmake
$ make

i would send you a patch, but i'm not qmake's biggest fan and haven't really used it much before

related to: #57

system: debian jessie. dependencies installed as listed in the help files.

**Comment by special** [comment]
These errors are actually pretty harmless. The files it's talking about are generated when lrelease is called at build-time, and they will be used when the resource compiler actually executes. From what I understand, the only effect here is the annoying messages, and that it may not generate the right Makefile rules to rebuild the resource if .ts files are changed.

One potential workaround ([source](https://stackoverflow.com/questions/4366898/how-to-specify-auto-generated-resource-files-to-qmake)) is to generate them at qmake-time with `system()` too. @rburchell, does that seem reasonable to you?

**Comment by myfreeweb** [comment]
Just built on FreeBSD 11-CURRENT, had to do this as well. This should be at least documented in `BUILDING.md`

**Comment by special** [comment]
@rburchell ping for an opinion on this problem

**Comment by PowerKiller** [comment]
I hit it too, lrelease worked for me.

**Comment by PowerKiller** [comment]
#269 and #184 is what I hit every time I try to build on Debian/Ubuntu. :(

**Comment by rburchell** [comment]
QMAKE_EXTRA_COMPILERS can probably be used to add an extra (automatic) target that will run lrelease at build time.

(sorry @special, for some reason I never saw the original messages at me)

**Comment by special** [comment]
Fixed by #503. Thanks.
