### ISSUE TITLE
running on debian jessie requires extra dependencies

### ISSUE THREAD

**Issue by esme-does-code** [ricochet-im/ricochet#185]
listed dependencies:
build-essential libssl-dev pkg-config libprotobuf-dev protobuf-compiler qt5-qmake qt5-default qtbase5-dev qttools5-dev-tools qtdeclarative5-dev (qtdeclarative5-controls-plugin does not exist for debian jessie)

then running gives the below. following this the only way to quit is by sending sigint or similar, since no window appears. solution is to install qml-module-qtquick-controls qml-module-qtquick-layouts qml-module-qtquick-window2 qml-module-qtquick-dialogs.

$ ./ricochet
QQmlApplicationEngine failed to load component
qrc:/ui/main.qml:4 module "QtQuick.Window" is not installed
qrc:/ui/main.qml:1 module "QtQuick" is not installed
qrc:/ui/main.qml:2 module "QtQuick.Controls" is not installed
qrc:/ui/main.qml:3 module "QtQuick.Layouts" is not installed
qrc:/ui/main.qml:4 module "QtQuick.Window" is not installed
qrc:/ui/main.qml:1 module "QtQuick" is not installed
qrc:/ui/main.qml:2 module "QtQuick.Controls" is not installed
qrc:/ui/main.qml:3 module "QtQuick.Layouts" is not installed
qrc:/ui/main.qml:4 module "QtQuick.Window" is not installed
qrc:/ui/main.qml:1 module "QtQuick" is not installed
qrc:/ui/main.qml:2 module "QtQuick.Controls" is not installed
qrc:/ui/main.qml:3 module "QtQuick.Layouts" is not installed
qrc:/ui/main.qml:4 module "QtQuick.Window" is not installed
qrc:/ui/main.qml:1 module "QtQuick" is not installed
qrc:/ui/main.qml:2 module "QtQuick.Controls" is not installed
qrc:/ui/main.qml:3 module "QtQuick.Layouts" is not installed

**Comment by special** [comment]
I think this was just (minutes ago) fixed by 643384b193824f87e6523a90c010ea690f0417bd.
