### ISSUE TITLE
Outbound connections fail when using a vanity address

### ISSUE THREAD

**Issue by gabedwrds** [ricochet-im/ricochet#186]
**NB**: Triggering this issue requires manually replacing Ricochet's hidden service key. Users sticking to the GUI won't see this. In fact, most users shouldn't mess with the internal config files at all.

Ricochet 1.1.0 asserts that its hidden service's DER-encoded public key is 140 bytes long. This seems to be true of keys generated by Tor, but vanity keys generated by software like [Scallion](https://github.com/lachesis/scallion) have large public exponents that require at least an extra byte.

To reproduce, try borrowing the PrivateKey from the example output on the Scallion page (obviously do not use this key for actual conversations) or generate your own and drop it into `config/data-0/private_key`.

When using a release build, this will silently prevent me from connecting to other clients. Note that other clients can still connect to me, so if I'm the only one using a vanity address, the only noticeable effect is that no one will ever receive my friend requests :'(

Using a debug build throws the following and dies when connecting to someone else (ricochet:tgicorjvtqbhcrjt) after starting the client:

> Attempting reconnection of socket to "tgicorjvtqbhcrjt.onion" 9878
> Granting 0 authentication as "tgicorjvtqbhcrjt.onion" to connection
> BUG: Unexpected size for encoded public key
> ASSERT: "something broke!" in file [src/protocol/AuthHiddenServiceChannel.cpp, line 198](https://github.com/ricochet-im/ricochet/blob/master/src/protocol/AuthHiddenServiceChannel.cpp#L198)
> Abort trap: 6

Adding `qDebug() << publicKey.toBase64() << publicKey.size();` before line 198 will dump a copy of the encoded public key and show that it's 141 bytes long.

Temporary fix: Replace the comparison on line 197 with `size() > 150`. I don't know if this is a sane value or if some other validation should be done, but I can now be successfully reached at `ricochet:gabedwrds3khg2uw`.

**Comment by special** [comment]
Neat.

The size of the key (which is all we actually care about) is enforced after decoding it. This check is just to avoid passing the ASN.1 parser anything that is obviously garbage. Tor does not bother to explicitly limit the encoded size in similar cases, although it will be under 512 bytes because of their protocol.

My intuition is that this check isn't important, but rejecting anything over 150-160 bytes is still a nice thing to do - on the off chance that it saves us from an ASN.1 decoding bug someday.

**Comment by special** [comment]
Actually, we're already more relaxed for inbound authentication:

AuthHiddenServiceChannel.cpp:285
```
    } else if (publicKeyData.size() > 180) {
```

So let's just make the outbound test the same as that one.
