### ISSUE TITLE
Ricochet is unusable on high DPI linux systems

### ISSUE THREAD

**Issue by special** [ricochet-im/ricochet#187]
Ubuntu 15.04, in a high DPI-enabled VM, with the "Scale for menu and title bars" option in display settings set to 2:

![screenshot](https://i.imgur.com/YSLLbYs.png)

What we're seeing here is that the system's font scale is used, but QtQuick isn't doing any DPI scaling, so anything with a pixel-defined size is completely wrong. This still happens with a build against the system Qt.

So, the question is how to get the DPI scaling behavior to work here like it does for e.g. Retina OS X.

**Comment by special** [comment]
Workaround:

```
QT_DEVICE_PIXEL_RATIO=2 ./ricochet
```

Where 2 matches `gsettings get org.gnome.desktop.interface scaling-factor`.

**Comment by special** [comment]
Qt and linux distributions have gotten quite a bit better at handling high dpi screens lately, and these bugs exist at a level that Ricochet doesn't have much control over.

Bugs are still welcome where it relates to our precompiled binaries.

**Comment by deadalnix** [comment]
I'm on windows and I'm having the exact same problem. What do I do ?
