### ISSUE TITLE
Look into compiler runtime hardening options

### ISSUE THREAD

**Issue by special** [ricochet-im/ricochet#190]
There are probably a handful of nifty compiler options for runtime hardening that we could use, both for Ricochet and the Qt builds. What are they?

**Comment by special** [comment]
mikeperry points out that gcc and clang have lots of neat sanitizers now: http://clang.llvm.org/docs/UsersManual.html#controlling-code-generation

    <mikeperry>	gcc 4.9.x also supports vtable verification
    <mikeperry>	GeKo has been working on Firefox builds with the gcc versions. I believe these cflags are for gcc 4.9.1:

See also https://trac.torproject.org/projects/tor/attachment/ticket/10599/mozconfig-ng

**Comment by ioerror** [comment]
I'd encourage you to do at mimimum what I do in tlsdate: https://github.com/ioerror/tlsdate/blob/master/configure.ac#L573
