### ISSUE TITLE
Use a bundled OpenSSL on OS X

### ISSUE THREAD

**Issue by special** [ricochet-im/ricochet#193]
The system OpenSSL library on OS X is too old, and Tor lacks some important features because of it. We should build against our own OpenSSL, like we do on every other platform.

**Comment by iEFdev** [comment]
Sorry to bump an old post, but may I ask how the bundled OpenSSL is retrieved? I just installed Ricochet (1.1.0) - I wanted to test it and seems very nice. I noticed that it used an old OpenSSL. On my system (10.7.5) the bundled version is backuped/renamed and a symlink (`usr/bin/openssl -> /usr/local/bin/openssl`) goes to my own installed version: **1.0.2d** _(eg latest)_ ...which is also before the old one in PATH.

From Prefs->Tor tab
```
Jul 25 00:22:39.579 [notice] Tor … … … running on Darwin with Libevent 2.0.21-stable, OpenSSL 0.9.8za and Zlib 1.2.5.

<snip />

Jul 25 00:23:07.000 [notice] We weren't able to find support for all of the TLS ciphersuites that we wanted to advertise. This won't hurt security, but it might make your Tor (if run as a client) more easy for censors to block.
Jul 25 00:23:07.000 [notice] To correct this, use a more recent OpenSSL, built without disabling any secure ciphers or features.
```

**Comment by special** [comment]
This is the library that the `ricochet` and `tor` binaries link to; not the `openssl` program. See:

```
$ otool -L /Applications/Ricochet.app/Contents/MacOS/tor
/Applications/Ricochet.app/Contents/MacOS/tor:
	/usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
```

Ricochet has to be [rebuilt](https://github.com/ricochet-im/ricochet/blob/master/BUILDING.md) to replace those, but keep in mind that it is not a security problem.

**Comment by iEFdev** [comment]
Aah… I see. Thank you. :+1:
