### ISSUE TITLE
Why are you signing the binaries, but don't sign the git commits?

### ISSUE THREAD

**Issue by l29ah** [ricochet-im/ricochet#199]
Git provides a nice integration with gnupg.

**Comment by special** [comment]
All releases already have a gpg-signed tag in git:

```
$ git tag --verify v1.1.0
object d87ca77bdcb887b57aa1963bbebeac66006f42bd
type commit
tag v1.1.0
tagger John Brooks <john.brooks@dereferenced.net> 1428709552 -0600

Version 1.1.0
gpg: Signature made Fri Apr 10 17:46:04 2015 MDT using RSA key ID 183C045D
```

Signing every commit would be messy, especially for commits where the committer is not the same person as the author. Would there be any compelling benefit to doing it on each one, instead of once per release?

**Comment by l29ah** [comment]
On Fri, Jun 12, 2015 at 08:10:46PM -0700, John Brooks wrote:
> Signing every commit would be messy, especially for commits where the committer is not the same person as the author. Would there be any compelling benefit to doing it on each one, instead of once per release?

Well, then one would be able to verify the authenticity of the current git repo slice, as a signed commit effectively signs the whole tree. Not sure if it's compelling enough tho.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments
