### ISSUE TITLE
Gentoo ebuild

### ISSUE THREAD

**Issue by l29ah** [ricochet-im/ricochet#200]
> If you're interested in helping to package Ricochet for common Linux platforms, please get in touch!

I'm here; wrote an ebuild for the git version.

**Comment by special** [comment]
Great! Is there anything we can do to help?

**Comment by l29ah** [comment]
On Fri, Jun 12, 2015 at 08:12:22PM -0700, John Brooks wrote:
> Great! Is there anything we can do to help?

Nope, everything just works (:

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by mark-in** [comment]
I confirm that l29ah's ebuild works.
BTW, I think that it should be mentioned where is this ebuild (overlay) located.
Overlay with `net-im/ricochet` is called (booboo)[https://github.com/l29ah/booboo]. One may add it via layman: `layman -a booboo`.
