### ISSUE TITLE
Packaging for common Linux distributions

### ISSUE THREAD

**Issue by special** [ricochet-im/ricochet#22]
We want Ricochet packaged for:
- [x] Debian
- [x] Ubuntu
- [x] Fedora (and other redhat systems)
- [x] Arch

In addition to writing the packages, each of these needs someone that is willing to volunteer to keep them up to date.

**Comment by cicku** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1264700 , I'm the reviewer.

But I still don't trust ricochet, not even tor/tox . :joy:

**Comment by special** [comment]
Ricochet is packaged for debian, ubuntu, fedora, and arch, thanks to package maintainers for each of those platforms.
