### ISSUE TITLE
Disconnect/Reconnect to Tor.

### ISSUE THREAD

**Issue by thebeline** [ricochet-im/ricochet#236]
When testing this, I was attempting to set my Proxy settings and messed up.  Ricochet proceeded to connect anyway, and now I can not disconnect Ricochet to adjust these settings.  Closing and Launching Ricochet simply connects with previous settings, and changing the configuration leaves it connect with no further attempts made to disconnect/reconnect.  Am I missing something?

**Comment by special** [comment]
You can go back through the Tor configuration by going to Preferences -> Tor -> Configure. It should put the new settings into effect right away, and they will be saved when you restart.

Does that not work? If so, could you paste the tor log shown after you try to change those settings?
