### ISSUE TITLE
Odd changing font size - after screen orientation change?

### ISSUE THREAD

**Issue by blitmap** [ricochet-im/ricochet#249]
Hi, I experienced an oddity where:

1) I was talking with someone
2) I locked the screen and set my **convertible** laptop down (it has a gyroscope thing?)
3) I unlocked  my laptop
4) I began talking again
5) The font size became huge!

I am on Windows 10, I believe this is related to the screen orientation changing while my laptop was locked, but when I unlocked it again I was using the same orientation when it happened.  I tried to reproduce this but it didn't occur again... here is a screenshot of what it looks like:

![bold](https://cloud.githubusercontent.com/assets/1560788/9292800/3e8c8e88-43c1-11e5-97ba-6c028e4908fe.png)

**Comment by special** [comment]
I don't think there's anything actionable here, especially after this much time. Hopefully new Qt/Windows is handling this case better -- if not, let's gather more info next time it happens and get it to Qt upstream.
