### ISSUE TITLE
Doesn't work at all on Windows 10...

### ISSUE THREAD

**Issue by fixingshit** [ricochet-im/ricochet#265]
Shows blank square. Flickering. No contents. Bizarre. I was hugely disappointed after not using Ricochet for a while and then realizing it's got a proper website, only to find that it doesn't run at all on Windows 10.

**Comment by special** [comment]
Someone else tested Windows 10 and reported no problems - maybe there's more than that going on.

Is this on a virtual machine? Do you have graphics drivers installed?

**Comment by sourcemaker** [comment]
No problems here. Windows 10, latest updates

**Comment by fixingshit** [comment]
Virtual machine, yes. No issues with any other programs. Non-exotic, vanilla installation.

**Comment by special** [comment]
Which kind of virtual machine? Virtualbox has been a problem before; maybe this is the same problem as #90?

**Comment by fixingshit** [comment]
VMware Player. How could it possibly have anything to do with this? It's a virtual machine. It runs whatever runs on the OS it runs inside.

**Comment by jiaweizhang** [comment]
@fixingshit Not all VMs are created equal. I've had issues with VMware Player before and it's not as reliable as other VMs. Try again with another VM and maybe it'll work.

**Comment by beemill** [comment]
i seem to have a similar issue described by fixingshit, except i'm testing this on an old laptop running vista. there are two screens open and both are blank. it works fine on the mac though.

**Comment by beemill** [comment]
I've just got it to work on Windows Vista, it had to do with the Colors bit setting under Display settings. It seems if you have it set to Colors "Medium (16 bit)" Ricochet won't show anything, just two blank windows, but changing it to "Highest (32 bit)" and everything finally shows.

**Comment by special** [comment]
Should be fixed by #367.
