### ISSUE TITLE
Signed build info on homepage

### ISSUE THREAD

**Issue by taoeffect** [ricochet-im/ricochet#268]
Standard practice for any security critical app to sign its builds with a GPG key.

When can we see signatures for the various builds here?

https://ricochet.im/

**Comment by taoeffect** [comment]
Oh wait, I just saw from the readme that builds are signed here: https://ricochet.im/releases/latest/

Will modify issue title to simply to request that this information be listed on the homepage

**Comment by special** [comment]
Moved over to the website repository. If you want to take a stab at adding it, all of the code is there. Thanks!

https://github.com/ricochet-im/website/issues/2
