### ISSUE TITLE
When adding new contacts the text sometimes does not appear to be legible (Debian 7)

### ISSUE THREAD

**Issue by Antaon** [ricochet-im/ricochet#27]
Specs: Torsion v1.0.0-10-g2c52502 on Debian 7 (64bit) in VirtualBox:

Repro Steps:
1) Open the Torsion binary and successfully connect to the Tor network.
2) Click the "Add Contact" button/icon.
3) Click into the "ID:" field and paste a valid id from the clipboard: (torsion:rs7ce36jsj24ogfw)

Results: The font for your own ID and the peers id can become illegible (see attached screenshot)

Expected Result: The fonts remain legible.

Notes:
This could be a result from the copied text font. (gedit: Monospace [size 11]). The torsion contact link was copied from the file "README" opened in gedit under gnome. The README file is packaged in the Torsion v1.0.0-10-g2c52502 for Debian 7 compressed file.
![torison_add_contact_font](https://cloud.githubusercontent.com/assets/5615671/2559088/a765dfbc-b769-11e3-8a66-e7bcb40486de.png)

**Comment by gabedwrds** [comment]
I just saw some similar font corruption:
![messages image 1834365870](https://cloud.githubusercontent.com/assets/1580619/7342256/033a6d30-ec7f-11e4-8f62-7fc8287fb944.png)

Setup:
* Ricochet 1.1.0 Linux x86_64 release package
* Kali Linux 1.1.0 (based on Debian 7)
* Running in VMware Fusion 7.1.1 on OS X 10.10.3
* VM was recently resumed before downloading and running Ricochet for the first time

I haven't been able to reproduce in the same VM or a fresh one.

**Comment by special** [comment]
Ricochet 1.1.1 uses Qt 5.5 and should solve another set of these problems. I haven't seen this one for awhile. Reopen if it's still applicable.
