### ISSUE TITLE
clarify copyright status of icons

### ISSUE THREAD

**Issue by infinity0** [ricochet-im/ricochet#277]
Hi, Debian rejected my package because I forgot to complete the copyright information. I'm doing that now.

`icons/LICENSE` mentions 4 extra authors and the Open Font License but it's unclear what they actually apply to. Does it mean they share joint authorship of `ricochet_icons.ttf`? Or that file is copyright Lawrence Eastland but uses portions of the other authors' work? (If the latter, then does he intend to relicense the file to CC-BY-SA-4.0 or keeping it as OFL? The first option might not be legal, I'm not sure.) Similarly, what about the other files? Also, what version of the OFL is it using? There is 1.1 and 1.0.

Also I think you can get rid of third party libraries in `LICENSE`, since you're not actually distributing the source code of them. It only makes things confusing and slows down people trying to figure out what the actual licensing information is.

**Comment by special** [comment]
> icons/LICENSE mentions 4 extra authors and the Open Font License but it's unclear what they actually apply to. Does it mean they share joint authorship of ricochet_icons.ttf?

Yes. ricochet_icons.ttf is a combination of those works.

> Or that file is copyright Lawrence Eastland but uses portions of the other authors' work? (If the latter, then does he intend to relicense the file to CC-BY-SA-4.0 or keeping it as OFL? The first option might not be legal, I'm not sure.) Similarly, what about the other files?

The other files are all the "R" icon, I believe. Those are copyright to Lawrence and CC-BY-SA-4.

> Also, what version of the OFL is it using? There is 1.1 and 1.0.

Good question.

> Also I think you can get rid of third party libraries in LICENSE, since you're not actually distributing the source code of them.

Ah, but we do distribute them with the binary versions of Ricochet, and the LICENSE file is used for that text as well.

I can try to clarify these documents at some point. PRs are always welcome too :)

**Comment by infinity0** [comment]
https://github.com/ricochet-im/ricochet/commits/master/icons/ricochet_icons.ttf

So you created that file using Fontello, not Lawrence Eastland? 

Looks the fonts are all SIL 1.1:

https://github.com/FortAwesome/Font-Awesome/blob/master/README.md
https://github.com/iconic/open-iconic/blob/master/FONT-LICENSE
https://github.com/danielbruce/entypo/commit/5529c0f81fe1e0506aa9f4c5f59b5ef7dfa4390d#diff-04c6e90faac2675aa89e2176d2eec7d8 SIL URL goes to "latest version" which at the date of the commit (2012) is 1.1 (release 2007)

http://www.justbenice.ru/s/WebSymbolsLiga-Regular.otf # mentions OFL1.1 in the file
$ sha256sum WebSymbolsLiga-Regular.otf 
7b74c36ce8da5956cb9f75568ba1106a2d6ee43ab51a86ca0d461e6e2407c1cf  WebSymbolsLiga-Regular.otf
$ strings WebSymbolsLiga-Regular.otf | grep 1.1
This Font Software is licensed under the SIL Open Font License, Version 1.1.

**Comment by infinity0** [comment]
OK, assuming you did create that file, I have all the information I need to resubmit the package. Also, it would be good if you could make these details more precisely clear in the `LICENSE` file.
