### ISSUE TITLE
Doesn’t handle zero supported versions correctly

### ISSUE THREAD

**Issue by shak-mar** [ricochet-im/ricochet#279]
From https://github.com/ricochet-im/ricochet/blob/master/doc/protocol.md#introduction-and-version-negotiation: “The server side of the connection must respond with a single byte for the selected version number, or 0xFF if no suitable version is found.” 
When running the following sh line though:
```sh
echo -e "\x49\x4D\x00" | torproxy […].onion 9878
```
It should respond with `ÿ` (`0xFF`), but instead closes the connection.

**Comment by s-rah** [comment]
I believe this is handled correctly by https://github.com/ricochet-im/ricochet/blob/master/src/protocol/Connection.cpp#L274-L277 - by definition trying to open a connection with 0 supported versions is a violation of the protocol, so closing the channel is correct action.

Probably could be clarified in the documentation though, something like "The total size is 3 plus the number of supported versions bytes. The number of supported versions must be at least 1."

**Comment by special** [comment]
I'm really glad someone is looking at it in this much detail!

I agree with @s-rah here. This one isn't a bug, because there's no way a connection with 0 supported versions could proceed. Closing it is a reasonable choice.
