### ISSUE TITLE
Ricochet Error: Cannot create directory /usr/bin/config

### ISSUE THREAD

**Issue by alanbortu** [ricochet-im/ricochet#290]
Hi,

I am trying to build a ricochet package for openSUSE here: https://build.opensuse.org/package/show/home:alanbortu/ricochet-im

The package seems to build fine but when I install it and try to run ricochet I get an error: "Cannot create directory: /usr/bin/config" (see: http://paste.opensuse.org/view/raw/896161).

I am new to RPM packaging so I suspect I am doing something wrong in my spec file. Does anyone have any idea what could be causing it?

Thanks.

**Comment by special** [comment]
For packaging, you probably want to add `DEFINES+=RICOCHET_NO_PORTABLE` to the qmake command.

**Comment by alanbortu** [comment]
Hi,

If you check the spec file (https://build.opensuse.org/package/view_file/home:alanbortu/ricochet-im/ricochet.spec?expand=1) I am using the following:

qmake-qt5 QMAKE_CFLAGS+="%{optflags}" QMAKE_CXXFLAGS+="%{optflags}" QMAKE_STRIP="/bin/true" DEFINES+=RICOCHET_NO_PORTABLE DESTDIR="%{buildroot}";

**Comment by special** [comment]
Hmm. That error means it thinks it's supposed to be portable, so something must not be working.

I don't see any whitespace between your `QMAKE_STRIP=".."` and `DEFINES+=`, other than the escaped linebreak. Could it be appending that parameter to the end of `QMAKE_STRIP`?

**Comment by alanbortu** [comment]
Ah that was it! What a silly mistake :)

Thanks for the quick resolution. The package has built now and works on my computer.

**Comment by special** [comment]
Awesome! Thanks for making it. Anything we can do to help get it into repositories?

**Comment by alanbortu** [comment]
@special  I think there were some hardcoded paths in the project files which caused issues when packaging. Some of the members on the build service channel expressed concern over that when I was asking for assistance and also suggested using CMAKE instead of QMAKE. I am not too familiar with packaging or QT so I cant give more detail but I am sure you can ask in #opensuse-buildservice on freenode and they can explain in more detail.

For the time being, the package builds and moves files to the appropriate location after install. I can confirm that its working for opensuse 42.1 :)

PS: I dont know if you have Fedora 22 packages but I went ahead and build that too. You can find them all either in the package link above or at: https://software.opensuse.org/package/ricochet

Thanks again!
