### ISSUE TITLE
Make "How To Contribute" a bit easier.

### ISSUE THREAD

**Issue by pureooze** [ricochet-im/ricochet#293]
Hi,

I think ricochet would benefit if there was a CONTRIBUTING.md file in the repo. Please see an example that mozilla has for Servo: https://github.com/servo/servo/blob/master/CONTRIBUTING.md

What is especially great about that file is when someone is submitting a PR on github a little box will appear at the top of the screen asking them to check the checklist in the CONTRIBUTING.md file. This makes it easy for new contributors to make sure they are following the project standard and for the maintainer because hopefully everyone will follow it.

It may also be helpful to have some kind of tag for easy/good for newbies type of issues. Another example from Servo: https://github.com/servo/servo/issues/8113.

These are just suggestions but I think they would help.

**Comment by rburchell** [comment]
Seems like a reasonable idea, although the contributor traffic here is much lower. If you'd like to PR a CONTRIBUTING file, I think we can look at getting something useful in shape there. For "easy" type issues, looking at the Ready milestone might be a useful place to look.

Sorry for the delayed response.

**Comment by pureooze** [comment]
@rburchell np :)
That sounds good, I will try and spin something up soon

**Comment by rburchell** [comment]
Great!
