### ISSUE TITLE
create RSS feed to let users know when updates are released

### ISSUE THREAD

**Issue by foss-** [ricochet-im/ricochet#296]
Since Ricochet has no internal update mechanism, it would be a good idea to create an RSS feed that serves as announcement mechanism for new releases.

That way it's easy for users to stay up to date and get note when a new version is out.

**Comment by special** [comment]
I agree! We should also brainstorm other ways users might want to find out about updates and important information. Is a mailing list worth it? A twitter account (other than my own)?

Github offers a releases atom feed automatically, so you can use that for now: https://github.com/ricochet-im/ricochet/releases.atom - we should link to that from somewhere too.

**Comment by foss-** [comment]
Didn't know this. Added that to my RSS reader. Will see in the future if that works. Thanks for bringing up this nice solution.

Maybe adding an update atom feed to the Get started section on https://ricochet.im/ would be nice. A dedicated ricochet twitter channel (potentially linked to the atom feed) re-tweeting any updates automatically, would be sweet.

**Comment by special** [comment]
Moved over to the website repo, so closing this one. Thanks.
