### ISSUE TITLE
Sound notification doesn't play if another sound is played in the system

### ISSUE THREAD

**Issue by Framartin** [ricochet-im/ricochet#298]
On Ubuntu 15.10 (ALSA 1.0.29), sound notifications of ricochet don't play if another software plays sounds at the same time (totem in my case). The following error message appeared on the console:

`ALSA lib pcm_dmix.c:1024:(snd_pcm_dmix_open) unable to open slave`

The notification is played when ricochet is the only software playing sound.

**Comment by rburchell** [comment]
Ricochet plays sound using QtMultimedia. If you can create a testcase and file a bug upstream there, then there might be a hope that someone with media expertise (which is not really part of the core knowledge here) can take a look.
