### ISSUE TITLE
ChatAcknowledge.accepted is not explained in protocol.md

### ISSUE THREAD

**Issue by shak-mar** [ricochet-im/ricochet#300]
See https://github.com/ricochet-im/ricochet/blob/master/doc/protocol.md#chatacknowledge.

**Comment by rburchell** [comment]
From looking at the code, "accepted" is whether or not the message is considered to have been delivered successfully, i.e. it didn't violate any constraints of the recipient's client.

That is, if accepted is false, then the message was delivered over the network, but for some reason, the receiving client rejected it.
