### ISSUE TITLE
"Check for Updates..." Sparkle style suto-update

### ISSUE THREAD

**Issue by taoeffect** [ricochet-im/ricochet#301]
For security critical programs an auto-update mechanism is critical.

If a vulnerability is found, then users must be able to find out about it and get the fix as soon as it's released.

On OS X this is accomplished via Sparkle.

Ricochet, unfortunately, is written in C++ (see #285). However, I know that [YouTube to MP3](http://www.mediahuman.com/youtube-to-mp3-converter/) (which appears to be censored from Google search results...) is a C++ program with a built-in autoupdater similar to Sparkle, so perhaps that or something else can be used.

**Comment by special** [comment]
See
