### ISSUE TITLE
Block External Entity Resolution (or force through Tor) 

### ISSUE THREAD

**Issue by s-rah** [ricochet-im/ricochet#303]
I'm not entirely sure this is possible, but I was writing up my ricochet fuzzing adventures and while thinking about deeper mitigations for https://github.com/ricochet-im/ricochet/pull/274 the idea came up.

Is it possible in Qt to either a) block the resolution of external resource e.g. <img> tags entirely or b) force the resolution through Tor?

Such an option would effectively mitigate any future HTML rendering bugs by turning, what is currently, an easy de-anonymization bug into an annoying, but mostly harmless, UX bug.

I had a quick search but haven't found a way so far, so I'm putting it out there in the hopes someone has an idea.

**Comment by special** [comment]
With 1956d6c, we now block all network requests originating from QML. That can't block traffic from Qt or anything else, but that's a problem we should handle with sandboxing when possible.
