### ISSUE TITLE
Minimize to systray?

### ISSUE THREAD

**Issue by Paradoxum** [ricochet-im/ricochet#305]
Could this be in a future release? it's pretty annoying closing the main window exits it.

Thanks

**Comment by 1ac0** [comment]
+1

Should be nice to be able minimaze app to systray with notification on the new message arrive, thanks.

**Comment by kolodziej** [comment]
This feature is in #260. This PR is waiting for merge since end of September.

**Comment by special** [comment]
Duplicate of #260
