### ISSUE TITLE
How do I find my own username?

### ISSUE THREAD

**Issue by Paradoxum** [ricochet-im/ricochet#306]
I can't see anywhere in the interface how to see my own UI, I can only get people to send me theirs once they register so I can add them.

Also, where is the user data stored? so I can migrate it with an install etc.

**Comment by rburchell** [comment]
There is no central username, just your address (ricochet:XXX) which you can see in the add contact dialog. You are named whatever your contact decided to call you (and that is almost certainly different for each contact).

**Comment by Paradoxum** [comment]
>which you can see in the add contact dialog.

thanks, that's what I was looking for. I didn't notice it was there.
