### ISSUE TITLE
[Request] Group conversations?

### ISSUE THREAD

**Issue by Paradoxum** [ricochet-im/ricochet#307]
I know nothing about the security behind it all, but would group conversations ever be possible? nothing huge, maybe like 5 people or something at a time. 

Thanks in advance.

**Comment by burdges** [comment]
Tor has no multi-party transport, so Ricochet must necessarily do group chats using pairwise transports.  There are a few issues to sort out around that depending upon the semantics people want, like introducing contacts vs. chats with contacts for whom you never learn the ricochet id.  It's maybe worth sorting out the crypto story first as this might impact those decisions slightly.

**Comment by s-rah** [comment]
I've been thinking a little bit about group conversations and wrote an initial draft which can be found https://github.com/ricochet-im/ricochet/pull/294 - it captures a few of the open questions @burdges alludes to. Still very much in the early design phase.

**Comment by burdges** [comment]
I'd imagine this thread could be closed in favor of that pull request then.

**Comment by special** [comment]
See also #54
