### ISSUE TITLE
end-to-end cryptography

### ISSUE THREAD

**Issue by 1ac0** [ricochet-im/ricochet#312]
Just an idea: how about end-to-end cryptography through gnupg with Ricochet?

**Comment by burdges** [comment]
Ricochet has end-to-end cryptography with forward secrecy from Tor hidden services.  Ricochet needs stronger cryptography with long-term forward secrecy, via an Axolotl ratchet, but that issue is https://github.com/ricochet-im/ricochet/issues/72
