### ISSUE TITLE
segmentation fault on close every time

### ISSUE THREAD

**Issue by kb100** [ricochet-im/ricochet#317]
I'm running version 1.1.1-2+b1 from debian sid. Every time I run ricochet, upon closing I get

```
zsh: segmentation fault  ricochet
```

I close ricochet using a keyboard shortcut that asks i3 window manager to kill the window via `i3-msg kill`

**Comment by special** [comment]
Can you run ricochet under gdb, kill it that way, and provide the backtrace?

**Comment by kb100** [comment]
(gdb) run
    Starting program: /usr/bin/ricochet 
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7fffe4bce700 (LWP 5484)]
    [New Thread 0x7fffe3f26700 (LWP 5488)]
    [New Thread 0x7fffdea9b700 (LWP 5495)]
    qrc:/ui/MainWindow.qml:89:17: QML Loader: Binding loop detected for property "active"
    ************* CLOSE WINDOW HERE ********************
    [Thread 0x7fffe3f26700 (LWP 5488) exited]
    [Thread 0x7fffe4bce700 (LWP 5484) exited]
    [Thread 0x7fffdea9b700 (LWP 5495) exited]
    
    Program received signal SIGSEGV, Segmentation fault.
    0x00007fffffffe280 in ?? ()
    (gdb) backtrace
    #0  0x00007fffffffe280 in ?? ()
    #1  0x00007ffff6f1db13 in ?? ()
       from /usr/lib/x86_64-linux-gnu/libasan.so.2
    #2  0x00007ffff6f1f689 in ?? ()
       from /usr/lib/x86_64-linux-gnu/libasan.so.2
    #3  0x00007ffff6f22c6d in ?? ()
       from /usr/lib/x86_64-linux-gnu/libasan.so.2
    #4  0x00007ffff6f23502 in ?? ()
       from /usr/lib/x86_64-linux-gnu/libasan.so.2
    #5  0x00007ffff2f222ef in __cxa_finalize (d=0x7ffff7165350)
        at cxa_finalize.c:56
    #6  0x00007ffff6e8e473 in ?? ()
       from /usr/lib/x86_64-linux-gnu/libasan.so.2
    #7  0x00007fffffffe970 in ?? ()
    #8  0x00007ffff7dea877 in _dl_fini () at dl-fini.c:252
    Backtrace stopped: frame did not save the PC
    
Let me know if there is anything else I can do to help you debug.

**Comment by special** [comment]
> #1  0x00007ffff6f1db13 in ?? ()
>    from /usr/lib/x86_64-linux-gnu/libasan.so.2

We no longer use ASAN on release builds.
