### ISSUE TITLE
Ricochet ignores language input setting

### ISSUE THREAD

**Issue by hsaito** [ricochet-im/ricochet#324]
I cannot activate language input (IME) on Linux, (Tested under Ubuntu 15.10, XFCE4)

Here's the repro case (in case of Japanese in my case):
1) Make sure the system is configured to support Japanese input
2) Change language input to Japanese, either by pressing shortcut (Ctl-Space) or by changing from the menu.
3) Ricochet disregards language setting and only allows an alpha numeric input.

This does not seem to reproduce in Windows, so it seems to be platform specific issue.

**Comment by special** [comment]
Are you using the linux static binaries, a package, or did you build Ricochet from source?

I suspect that the static package might not have IME support. Using the system's copy of Qt instead should help.

**Comment by hsaito** [comment]
It was through the package. I will try to brew my own binary from the source and see!

**Comment by hsaito** [comment]
I've tracked down this down to, like you said, something to do with static binary. (Static binary on Qt is somewhat of an ugly business as it would require plugin like libfcitxplatforminputcontextplugin.so or libibusplatforminputcontextplugin.so depending on the input system in use.)

I haven't actually confirmed this would work with when dynamically linked (there seems to be bit of dependencies I have to fulfill to compile Ricochet without runtime errors) but from what I found out about the way the Qt libraries work, this seems to be the reason.

**Comment by hsaito** [comment]
Building from the source did a trick!
