### ISSUE TITLE
Doesn't work on my windows 7 ultimate

### ISSUE THREAD

**Issue by anotherclient** [ricochet-im/ricochet#325]
ricochet can't starting. There comes amessage window:

> > An error occurred while loading the Ricochet UI.  You might be missing plugins or dependensy packages >>

What can i do ?
Thanks

**Comment by special** [comment]
Are you using the Ricochet installer? My first suggestion is to reinstall from there - most likely, some file was lost or accidentally deleted.

We haven't had any other reports of issues on Windows 7.

**Comment by pitab** [comment]
same problem here:
Name der fehlerhaften Anwendung: ricochet.exe, Version: 1.1.2.0, Zeitstempel: 0x56bd53b1
Name des fehlerhaften Moduls: ig4icd32.dll, Version: 8.15.10.1892, Zeitstempel: 0x4a9eb9c4
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00031fa6
ID des fehlerhaften Prozesses: 0xcdc
Startzeit der fehlerhaften Anwendung: 0x01d16db633e84d28
Pfad der fehlerhaften Anwendung: G:\Lupo8\Lupo_PenSuite_v2016_Full\MyApps\Ricochet\ricochet.exe
Pfad des fehlerhaften Moduls: C:\windows\system32\ig4icd32.dll
Berichtskennung: 75cea998-d9a9-11e5-80f8-002622b671f0

**Comment by peteneve** [comment]
Same problem here.

**Comment by special** [comment]
The Windows build process has changed since 1.1.2, hopefully in a way that should resolve problems like this. Please open a new bug if you're still having trouble in the latest version.
