### ISSUE TITLE
Blank window on Windows 7 + VMWare

### ISSUE THREAD

**Issue by Da-Cow** [ricochet-im/ricochet#328]
I have a very interesting (odd) issue.

Ricochet: portable, latest version 1.1.1.0  (using installer version has same results).

Interestingly, the problem does NOT exist using version 1.1.0.

OS: Windows 7 Home Premium, Service Pack 1, all service packs + updates installed. Running as a VM inside a Windows 7 Home Premium host, using VMWare Workstation 10.0.7 build-2844087.

Antivirus used is Windows Security Essentials antivirus with default options and current definitions.

Firewall is Windows Firewall. All ports are open; it's effectively off.

Network adapter is standard VMWare. Protocols used are TCP/IP 4  (IPv6 is disabled). All MS sharing, network discovery and file-sharing client protocols are off. Network adapter is in standard VMWare default mode, i.e. "bridged" to the host adapter.

Display: The VM is using standard (default) display options for Win7 running inside VMWare, i.e.:
- "VMWare SVGA 3D" Windows 7 driver, provider "VMware, Inc.", version 7.14.1.5026
- DLLs used are  "vm3dgl.dll" version 2.4.04.0;  "vm3dum.dll" version 7.14.01.5026; "vm3dmp.sys" version 7.14.01.5026
- in VMWare Workstation settings: 3D graphics acceleration enabled
- in Windows: 32-bit color, 60 Hz refresh
- DirectX version 11
- resolution 1362x600

DirectX diag file contains much more detailed information about the status of the VM. Please see it for this information: (dxdiag.txt)
[DxDiag.txt](https://github.com/ricochet-im/ricochet/files/93880/DxDiag.txt)

Windows 7 systeminfo dump is here: (systeminfo.txt): 
[systeminfo.txt](https://github.com/ricochet-im/ricochet/files/93891/systeminfo.txt)

The issue is that when Ricochet is run, there is a blank window. Nothing else occurs - there are no error messages, dialog boxes, or Event Log issues logged. Here's a screenshot: (ricochet.gif)
![ricochet](https://cloud.githubusercontent.com/assets/16752823/12384308/4e8d3d32-bd7e-11e5-9b8b-16dad3f3788c.gif)

Right-clicking, keyboard tapping. or any other input fails to change this. The only thing to do is to click the "X" on the top right hand corner, whereupon Ricochet exits immediately without any hesitation.

Logged-on user is VM local Administrator. The VM is not part of a Windows domain; it's standalone.

Changing display settings (e.g. refresh rate, color bit-depth, acceleration settings, resolution) does nothing to fix the issue.

Running Ricochet in Compatibility Mode doesn't help either (I tried all possible combinations - XP mode, Vista mode, as Administrator, in 256 colors, disabling visual themes, etc.)

The same Ricochet version launches fine when run on the host (physical) PC, which is an Acer laptop running a similarly-configured Windows 7 version as the VM guest. It has an Intel HD Graphics adapter with default, normal, display settings. Here's its DXDiag dump: (dxdiag_physical_host.txt)
[DxDiag_physical_host.txt](https://github.com/ricochet-im/ricochet/files/93887/DxDiag_physical_host.txt)

**Comment by special** [comment]
Looks like some kind of OpenGL issue with Qt. Hard to guess exactly what that might be. You can try [1.1.2](https://ricochet.im/releases/1.1.2) - it has a newer version of Qt.

If that doesn't help, you can try changing the opengl backend:

Open cmd.exe, run `set QT_OPENGL=angle`, and then run ricochet from that command line. You can also try `QT_OPENGL=software` or `QT_OPENGL=desktop` (which is the one it's most likely using now).

**Comment by special** [comment]
Probably fixed by Qt upgrades or #367. Please open a new bug if there are still problems with the latest version.
