### ISSUE TITLE
API/library?

### ISSUE THREAD

**Issue by cwage** [ricochet-im/ricochet#329]
Is the codebase at all poised such that the communication portion could be separated out into a library/API separate from the GUI?

This might be nice, long-term, to facilitate other clients -- for example, i'd love to have a console/text client, and surely it'd facilitate other platforms (mobile comes to mind).

Apologies if this is already suggested/mentioned elsewhere.

**Comment by s-rah** [comment]
Hi! You might be interested in https://github.com/ricochet-im/ricochet/wiki/Third-Party-Implementations-of-the-Ricochet-Protocol which lists a few 3rd party implementation of the ricochet protocol - in various states of development.

**Comment by cwage** [comment]
awesome, thank you!

**Comment by whatisgravity** [comment]
I'm also interested in this thanks

**Comment by lammas** [comment]
+1 for a C++ library

I'm considering rolling my own lib for my language of choice, but it would be much easier maintenance wise if i could just create bindings for an upstream C++ library.

**Comment by whatisgravity** [comment]
I rewrote the code in golang, Ill release it soon.

**Comment by JamesHealdUK** [comment]
A Java library defenitely wouldnt go a miss. If I ever get time and my skills (and understanding of the Ricochet protocol...) are good enough by then, Id be more than happy to contribute to development of an Android app.

**Comment by rburchell** [comment]
There's ongoing efforts for this with https://github.com/ricochet-im/ricochet-go, and we have https://github.com/ricochet-im/ricochet/wiki/Third-Party-Implementations-of-the-Ricochet-Protocol to track third party implementations, so I think we can close this one.
