### ISSUE TITLE
Ricochete 1.1.1 crashes on startup (Windows 7 Ultimate)

### ISSUE THREAD

**Issue by czsssss** [ricochet-im/ricochet#331]
After Ricochet was installed, it won't run. The box that allows user to select connecting through tor normally or through bridge is blank, then there's a popup says that Ricochet.exe has stopped working.

Here's the appcrash data. Is there anything else I can provide?

  Problem Event Name:	APPCRASH
  Application Name:	ricochet.exe
  Application Version:	1.1.1.0
  Application Timestamp:	55ebab0e
  Fault Module Name:	ig4icd32.dll
  Fault Module Version:	8.15.10.1883
  Fault Module Timestamp:	4a969adc
  Exception Code:	c0000005
  Exception Offset:	00031fa6
  OS Version:	6.1.7600.2.0.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by special** [comment]
Sounds similar to the problem in https://forum.qt.io/topic/18053/qt-opengl-app-crashing-in-ig4icd32-dll/2, but this doesn't point to any particular solution. The crash in ig4icd32.dll means that your Intel graphics driver is causing problems.

The next (imminent) [release](https://ricochet.im/releases/1.1.2/) of Ricochet updates Qt - there's a chance that will solve the issue. Upgrading your graphics drivers could also help.

**Comment by bungabunga** [comment]
the same is also happening to my friend on Windows 7 with Intel graphic, even on 1.1.2. sadly his graphics driver can not be upgraded.

how do you log a crash on windows?

**Comment by Aeyoun** [comment]
Seeing the same problem. Unable to update drivers on the device (it’s admittedly ancient).

**Comment by special** [comment]
Closing this in favor of #367, which is hopefully the general solution to graphics driver issues on Windows.
