### ISSUE TITLE
Feature requests - mobile, self-destruct, hidden text

### ISSUE THREAD

**Issue by davidlatapie** [ricochet-im/ricochet#335]
* iOS and Android support, like Signal
* customisable self-destruct timer, like Wickr
* hidden text (notification reveals nothing and you must click on a lock to see the actual text), like Wickr

**Comment by special** [comment]
* #115
* There is no cryptographic or meaningfully enforceable concept of self-destructing messages; it's equivalent to politely asking your peer to clear their backlog every few minutes. Ricochet doesn't save messages, so this happens every time it's closed. See also #273.
* Ricochet doesn't show message contents in notifications anywhere. I suppose I could imagine value in having to click to reveal message text in some shoulder-surfing scenario, but it seems like the smarter choice is to not have private conversations and leave Ricochet up when someone is shoulder-surfing you. I don't really see a compelling UX case.

**Comment by davidlatapie** [comment]
Your answer completely satisfies me.
