### ISSUE TITLE
OpenSSL issue

### ISSUE THREAD

**Issue by Redback812** [ricochet-im/ricochet#346]
I have El captain OSX and was watching the log and this info showed up !

I'm not sure if this is an issue?

Feb 19 18:23:15.787 [notice] Tor v0.2.7.6 running on Darwin with Libevent 2.0.22-stable, OpenSSL 1.0.1r and Zlib 1.2.5.
Feb 19 18:23:15.788 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Feb 19 18:23:15.789 [notice] Read configuration file "/Users/~/Library/Application Support/Ricochet/Ricochet/tor/default_torrc".
Feb 19 18:23:15.791 [notice] Read configuration file "/Users/~/Library/Application Support/Ricochet/Ricochet/tor//torrc".
Feb 19 18:23:15.812 [notice] Opening Control listener on 127.0.0.1:0
Feb 19 18:23:15.812 [notice] Control listener listening on port 56133.
Feb 19 18:23:15.813 [notice] DisableNetwork is set. Tor will not make or accept non-control network connections. Shutting down all existing connections.
Feb 19 18:23:15.813 [warn] Fixing permissions on directory /Users/~/Library/Application Support/Ricochet/Ricochet/tor/
Feb 19 18:23:15.000 [notice] We were built to run on a 64-bit CPU, with OpenSSL 1.0.1 or later, but with a version of OpenSSL that apparently lacks accelerated support for the NIST P-224 and P-256 groups. Building openssl with such support (using the enable-ec_nistp_64_gcc_128 option when configuring it) would make ECDH much faster.
Feb 19 18:23:15.000 [notice] Bootstrapped 0%: Starting
Feb 19 18:23:15.000 [notice] Delaying directory fetches: DisableNetwork is set.
Feb 19 18:23:19.000 [notice] New control connection opened from 127.0.0.1.
Feb 19 18:23:19.000 [notice] DisableNetwork is set. Tor will not make or accept non-control network connections. Shutting down all existing connections.
Feb 19 18:23:19.000 [notice] DisableNetwork is set. Tor will not make or accept non-control network connections. Shutting down all existing connections.
Feb 19 18:23:25.000 [notice] Opening Socks listener on 127.0.0.1:0
Feb 19 18:23:25.000 [notice] Socks listener listening on port 56135.
Feb 19 18:23:25.000 [notice] Bootstrapped 5%: Connecting to directory server
Feb 19 18:23:32.000 [notice] Bootstrapped 10%: Finishing handshake with directory server
Feb 19 18:23:34.000 [notice] Bootstrapped 15%: Establishing an encrypted directory connection
Feb 19 18:23:34.000 [notice] Bootstrapped 20%: Asking for networkstatus consensus
Feb 19 18:23:35.000 [notice] Bootstrapped 25%: Loading networkstatus consensus
Feb 19 18:23:45.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
Feb 19 18:27:07.000 [notice] Bootstrapped 40%: Loading authority key certs
Feb 19 18:27:08.000 [notice] Bootstrapped 45%: Asking for relay descriptors
Feb 19 18:27:08.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/7199, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of exit bw = 0% of path bw.)
Feb 19 18:27:10.000 [notice] Bootstrapped 50%: Loading relay descriptors
Feb 19 18:27:17.000 [notice] Bootstrapped 55%: Loading relay descriptors
Feb 19 18:27:22.000 [notice] Bootstrapped 61%: Loading relay descriptors
Feb 19 18:27:25.000 [notice] Bootstrapped 70%: Loading relay descriptors
Feb 19 18:28:23.000 [notice] Bootstrapped 76%: Loading relay descriptors
Feb 19 18:28:23.000 [notice] Bootstrapped 80%: Connecting to the Tor network
Feb 19 18:28:23.000 [notice] Bootstrapped 90%: Establishing a Tor circuit
Feb 19 18:28:26.000 [notice] Tor has successfully opened a circuit. Looks like client functionality is working.
Feb 19 18:28:26.000 [notice] Bootstrapped 100%: Done

**Comment by mapmeld** [comment]
Looks safe and up-to-date - the messages says you lack "accelerated support" (as in speedier calculation of those algorithms) but you do have support for those algorithms in your version of OpenSSL, 1.0.1r, which was released 28 Jan 2016

**Comment by special** [comment]
There is no security impact to that notice, but it is something we could and should fix. See #309.

Thanks
