### ISSUE TITLE
No window appears on Fedora 22

### ISSUE THREAD

**Issue by lpar** [ricochet-im/ricochet#348]
```
% ./ricochet 
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version
```

...and then nothing. It creates a `config` directory, but no GUI appears. Nothing useful in system logs.

```
% locate i965_dri.so
/usr/lib64/dri/i965_dri.so
```

**Comment by Aeyoun** [comment]
Works for me in Fedora 23 with ATI and Intel graphics drivers. Run `glxinfo` and see if you get any warnings about drivers?

**Comment by lpar** [comment]
No, no warnings. [Full output here](https://gist.github.com/lpar/4afc2dc632387b599b1c). Also, WebGL works, which is pretty picky.

**Comment by special** [comment]
One good solution would be to have a proper RPM package in Fedora, like we do in Debian. The static build is more likely to have issues than your system Qt.

#367 is also a promising solution.
