### ISSUE TITLE
Windows 10 Enterprise - doesn't even load the software

### ISSUE THREAD

**Issue by Eloqi** [ricochet-im/ricochet#358]
Error Message : 
Name der fehlerhaften Anwendung: ricochet.exe, Version: 1.1.2.0, Zeitstempel: 0x56bd53b1
Name des fehlerhaften Moduls: libGLESv2.dll, Version: 0.0.0.0, Zeitstempel: 0x56bd48fc
Ausnahmecode: 0xc000001d
Fehleroffset: 0x000a137c
ID des fehlerhaften Prozesses: 0x19a8
Startzeit der fehlerhaften Anwendung: 0x01d16e1e984d37fa
Pfad der fehlerhaften Anwendung: C:\Users\MYNAME\AppData\Local\Ricochet\ricochet.exe
Pfad des fehlerhaften Moduls: C:\Users\MYNAME\AppData\Local\Ricochet\libGLESv2.dll
Berichtskennung: 8a8cd77b-0db7-4d97-9a97-1af678f1582a
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

I installed the software (not portable)
and i cant figure out where the problem is. even reinstalled it. restarted my PC.
Hope somebody can help
Win10 is up to date. If you need any more infos ask for them and i try to provide them.

**Comment by special** [comment]
This is an OpenGL implementation issue. Hopefully we can solve it with the solution in #367. Closing this.
