### ISSUE TITLE
Investigate whether #SailfishOS mobile app would be plausible

### ISSUE THREAD

**Issue by jjaone** [ricochet-im/ricochet#361]
As the Ricochet seems have C++/QML implementations in this repo but the app iis not yet on any mobile platform, would it be possible to start developing a mobile app to #SailfishOS (Jolla's #opensource #Qt/QML-based security and privacy-aware #Linux mobile OS)..? I'd be willing to help and contribute to such a porting task or project.

**Comment by rburchell** [comment]
I don't think you need to use hashtags on a bug tracker ;)

Duplicate of #115.

**Comment by jjaone** [comment]
Thanks for pointing out that this request actually is a duplicate and that there are some interest for mobile apps for some platforms. I'd be really interested in SailfishOS native app of Ricochet and am willing to start coding the back-end or the UI for this. I'll join the conv in #115 and will let them know.

Sorry about hashtags, being using them in Twitter and other forums when referering those 'brand'-names and they just got copied here by accident..

**Comment by jjaone** [comment]
Closing the issue because of being addressed in #115 (of which this is a duplicate).

**Comment by rburchell** [comment]
Thanks, good to see some interest :)
