### ISSUE TITLE
Can't start Ricochet on Windows 10

### ISSUE THREAD

**Issue by cidrepivoine** [ricochet-im/ricochet#375]
Hello,

After downloading Ricochet (from the website), the application doesn't even start.
I am far from an expert but willing to use the program. Since there is really little information/guidance on how to use Ricochet on the website, I ask my question here (not knowing if that is the good place).
Are there known bugs or competing apps I should know about on Windows 10?

Thanks!

**Comment by void-in** [comment]
What error message you receive? What exactly happens when you run the setup? "the application doesn't even start" is very vague to debug. You have to provide additional details in order for someone to debug the problem.

**Comment by cidrepivoine** [comment]
I download the program on the website. Then I just tried to open by double clicking on the icon. And nothing happens: no specific message or anything. I am sorry if I missed something on how to set up Ricochet and/or github is not the place to address that. Little info is available on the website, I must say.

**Comment by zimorodokan** [comment]
The same problem, but only on one computer. On other it works.
May be it is need Visual C library or other.

Назва аварійного застосунку: ricochet.exe, версія: 1.1.2.0, позначка часу: 0x56bd53b1
Назва аварійного модуля: libGLESv2.dll, версія: 0.0.0.0, позначка часу: 0x56bd48fc
Код винятку: 0xc000001d
Зсув помилки: 0x000a137c
Код аварійного процесу: 0x2bec
Час запуску аварійного застосунку: 0x01d176508818470a
Шлях до аварійного застосунку: C:\temp\Ricochet\ricochet.exe
Шлях до аварійного модуля: C:\temp\Ricochet\libGLESv2.dll
Код звіту: 88c3803f-8d90-4550-b7bb-b51ae7643e37
Сегмент пам'яті з помилкою: 107963590327, тип 1
Ім'я події: APPCRASH
Відповідь: Недоступно
Код CAB-файлу: 107563588673

Підпис проблеми:
P1: ricochet.exe
P2: 1.1.2.0
P3: 56bd53b1
P4: libGLESv2.dll
P5: 0.0.0.0
P6: 56bd48fc
P7: c000001d
P8: 000a137c
P9: 
P10: 

Вкладені файли:
C:\Users\...\AppData\Local\Temp\WERDF6E.tmp.WERInternalMetadata.xml
C:\Users\...\AppData\Local\Temp\WEREAE8.tmp.appcompat.txt
C:\ProgramData\Microsoft\Windows\WER\Temp\WEREB76.tmp.mdmp
C:\Users\...\AppData\Local\Temp\WEREFDC.tmp.WERDataCollectionFailure.txt

Можливе розташування файлів:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_ricochet.exe_386e50f33d28cf328f865ef78f42d44747725aaa_6e4d8c03_cab_278af44e

Символ аналізу: 
Повторний пошук вирішення: 0
Код звіту: 88c3803f-8d90-4550-b7bb-b51ae7643e37
Стан звіту: 8
Гешований сегмент пам'яті: c9608f277d109722cd3cfd5c3fe81c85

**Comment by void-in** [comment]
Perhaps this is the same issue as https://github.com/ricochet-im/ricochet/issues/367

**Comment by cidrepivoine** [comment]
Ok thank you for that. I looked at #367 but it is beyond my expertise. I guess I will have to wait for a more stable and user(/non-expert)-friendly version of the software.

**Comment by special** [comment]
I'm considering all libGLES issues on Windows to be part of #367. Closing this ticket in favor of that one - thanks for the report.
