### ISSUE TITLE
Command Line interface?

### ISSUE THREAD

**Issue by Vwrkagya15cb6Pi** [ricochet-im/ricochet#376]
Hi,
Any intention to create a command line interface for Ricochet? Would be really useful for people that don't want QT5 packages installed or for less memory consumption.
Something simple as irssi would be enough, I think.
The commands input could be as in IRC too:

/addcontact [-id] [-name] [-message]

/printID [print your own ID]

/join [id] [name]

/status [id] [name] [all]

/version

/help

The contacts could be stored in a ".contacts"  file.
This would remove sounds, icons and QT packages for a minimal build.

**Comment by special** [comment]
This is out of scope of the primary ricochet implementation here, but it sounds like a great project to do based on one of the [other protocol implementations](https://github.com/ricochet-im/ricochet/wiki/Third-Party-Implementations-of-the-Ricochet-Protocol).

**Comment by wfr** [comment]
My fork of Ricochet implements an IRC server: [ricochet-irc](https://github.com/wfr/ricochet-irc/)
![ricochet-irc screenshot](https://raw.githubusercontent.com/wfr/ricochet-irc/d25b1b31ff8169da9f6dcc9edbb9c81be6e94b89/doc/irc/ricochet-irc.png)

The binary of `ricochet-irc` only links to the headless parts of Qt. It does not depend on GUI code.
I hope this helps!
