### ISSUE TITLE
Allow sandboxes to disable write-execute allocation

### ISSUE THREAD

**Issue by special** [ricochet-im/ricochet#380]
If we disable the QML V4 engine's JIT, sandboxes will be able to prevent write-execute memory for Ricochet. We probably don't do any javascript intensive enough for this to have a performance impact.

This is possible by setting `QV4_FORCE_INTERPRETER=1`, but a code-based way to do it would be more useful.

**Comment by ioerror** [comment]
I've sent a patch.

**Comment by special** [comment]
Fixed by 92d9d3de04d371bcc58b023db49b1e423d018a35
