### ISSUE TITLE
multiple ricochet IDs

### ISSUE THREAD

**Issue by DirectorX** [ricochet-im/ricochet#381]
there is a way to use 2 or more ricochet IDs?

**Comment by kolodziej** [comment]
Yes, but its a bit problematic -- you have to move your two (or more) profiles between directory which stores Ricochet's config.
I'm planning new version of profile which will be in a form of one, encrypted file. Ricochet will have option to switch between different profiles on startup. I have commited an issue #254 in which I describe my point of view. First step assume that we will have one profile in one file. When it will be known what we want to do with multi-device problem, profile will change.

**Comment by DirectorX** [comment]
Update: I notice that when I starts ricochet with an argument  it creates a directory (named after the argument) and treat it like a working directory. This way I can use multiple identities

**Comment by special** [comment]
Sounds like a good temporary solution. #235 and #99 are also related to this.
