### ISSUE TITLE
Get Ricochet working on Subgraph OS

### ISSUE THREAD

**Issue by special** [ricochet-im/ricochet#387]
See also https://github.com/subgraph/subgraph-os-issues/issues/9

They need to:

* Disable ASAN (see also #341)
* Have ADD_ONION (pull request at #385)
* Tell Ricochet to use the system instance of Tor (pull request at #386)

I bet they would also appreciate:

* Disabling the JIT to disallow write-execute memory (#380)

**Comment by delaRosa12345** [comment]
Cool! Looking forward to this!

**Comment by ioerror** [comment]
I've tested both outstanding branches, I've disabled ASAN (patch sent to @special via secure channel) and I've also taken a stab at disabling two different JITs in Ricochet's use of QT (patch sent to @special).

This allows me to run Ricochet on SubgraphOS and is a preliminary port to working on PaX/Grsecurity enabled kernels.

As a side note: there are some issues running inside of the OZ sandboxing framework - but it works perfectly, with no PaX exceptions outside of OZ. With OZ - you'll oddly need to set PaX exceptions.

First, you'll want a basic oz policy:
```
cat << 'EOF'> /var/lib/oz/cells.d/ricochet.json
{
"path": "/usr/bin/ricochet"
, "watchdog": ["ricochet"]
, "allowed_groups": ["debian-tor"]
, "xserver": {
	"enabled": true
	, "enable_tray": false
	, "audio_mode": "pulseaudio"
}
, "networking":{
	"type":"empty"
	, "sockets": [
		{"type":"client", "proto":"tcp", "port":9050}
		, {"type":"client", "proto":"tcp", "port":9051}
	]
}
, "whitelist": [
	{"path":"${HOME}/.config/ricochet", "can_create":true}
	, {"path":"${HOME}/.local/share/Ricochet", "can_create":true}
]
, "environment": [
	 {"name":"TOR_CONTROL_PORT"}
]
}
EOF
```

Then you'll want to install this profile and set the PaX flags:
```
oz-setup install ricochet
setfattr -n user.pax.flags -v "emr" /usr/bin/oz/ricochet
```

If you'd prefer to use ```paxrat``` you can add the following to the paxrat config ```/etc/paxrat/paxrat.conf```:
```
  "/usr/bin-oz/ricochet": {
    "flags": "emr"
  }
```

Once @special merges my two patches and you run git tip, it should be possible to run ricochet on SubgraphOS!
