### ISSUE TITLE
Add control socket

### ISSUE THREAD

**Issue by ioerror** [ricochet-im/ricochet#393]
Ricochet should use `/var/run/tor/control` when `ricochet` is in the `debian-tor` user group on Debian Gnu/Linux rather than `127.0.0.1:9051` for control port access.

**Comment by special** [comment]
This is implemented in the (not yet merged) unix branch under #225. If `TOR_CONTROL_SOCKET` is set in environment, it will be used.

Closing this as a duplicate of #224 and #225.
