### ISSUE TITLE
Linux x86_64 statically compiled binary issues/suggestions

### ISSUE THREAD

**Issue by sugoiuguu** [ricochet-im/ricochet#398]
Not sure if these are platform wide, but here are some things that should be addressed:

· There's no support for accentuation on the client input box (things like 'é' or 'ã' simply can't be typed)
· The mouse scrolling is a bit slow, since it seems the Qt interface is geared at touch devices (talking about the ability to scroll with mouse 1)
· You're able to select multiple lines of text at the same time, most likely because different text boxes are used for each message
· Maybe use Qt forms instead of qml, to better cope with these problems

That's all, I believe. Thanks.

**Comment by special** [comment]
> · There's no support for accentuation on the client input box (things like 'é' or 'ã' simply can't be typed)

What do you expect for this on your platform? Does it work in other Qt applications?

**Comment by sugoiuguu** [comment]
> What do you expect for this on your platform?

I expect to be able to input diacritics. Pasting a character from the clipboard, say, 'é', works fine, but not actually typing it in. The problem likely rises from dead keys, since I'm guessing ricochet catches key events. On a side note, I have friends who run Windows and OSX on their machines, have tried ricochet, and haven't run into my problem.

> Does it work in other Qt applications?

No problem. I use skype on x86_64 Linux, and haven't had issues.

**Comment by special** [comment]
For the diacritics issue, see #60 - there's a lead on how to solve it now. Thanks for bringing that up.

I made #401 about selecting multiple lines of text. The scrolling issues are unfortunate, but I'm hoping we can solve them with a newer version of Qt in the future.

Closing this in favor of those more specific bugs. Thanks!
