### ISSUE TITLE
Possible to set Ricochet Id?

### ISSUE THREAD

**Issue by naomik** [ricochet-im/ricochet#408]
My friend has been fussing with his Linux install, and each time he reinstalls he gets a new Ricochet Id.

Is it possible to somehow preserve your old Ricochet Id and set it after reinstalling the client? I imagine there's some generated keys to go along with it.

Thanks for any advice.

**Comment by special** [comment]
Sure - he just needs to back up and restore Ricochet's configuration directory. There's discussion of making this easier on #235.

The files will likely be under `~/.local/share/Ricochet/` on his system. Copying that entire directory to the new install should preserve everything.

**Comment by naomik** [comment]
@special thank you very much. For my future reference, could you tell me where Ricochet stores this information on **OSX**?

**Comment by special** [comment]
@naomik It's generally under `~/Library/Application Support/Ricochet`. Both of these are the standard configuration paths on their respective platforms.

**Comment by naomik** [comment]
Thanks 👍
