### ISSUE TITLE
LLVM Error

### ISSUE THREAD

**Issue by cosmicpuppet** [ricochet-im/ricochet#409]
When I start the program it output me this error message

OS: Debian Jessie 64bits

It's thesame when I build from sources.

`LLVM ERROR: Cannot select: intrinsic %llvm.x86.sse41.pblendvb`

Debug infos (sorry I have no experience with gdb):

```
[New Thread 0x7ffff3502700 (LWP 5446)]
[New Thread 0x7ffff2af6700 (LWP 5448)]
[New Thread 0x7fffe9ea1700 (LWP 5449)]
[New Thread 0x7fffe96a0700 (LWP 5450)]
LLVM ERROR: Cannot select: intrinsic %llvm.x86.sse41.pblendvb
[Thread 0x7fffe96a0700 (LWP 5450) exited]
[Thread 0x7fffe9ea1700 (LWP 5449) exited]
[Thread 0x7ffff2af6700 (LWP 5448) exited]
[Thread 0x7ffff3502700 (LWP 5446) exited]
```

**Comment by special** [comment]
This is llvmpipe (software opengl implementation), failing for some reason related to your system or environment.

Ricochet's upcoming 1.1.4 release has a pure software renderer, which should avoid these problems. See #367 for more.
