### ISSUE TITLE
UI doesn't display characters correctly

### ISSUE THREAD

**Issue by infinity0** [ricochet-im/ricochet#411]
Forwarding from https://bugs.debian.org/813354, feel free to reply either here or to the OP if you need to ask them questions (be sure to CC 813354@bugs.debian.org in that case).

~~~~
When launching the program by command 
`ricochet`, the font displayed on UI (as shown at http://imgur.com/8kfxw9p) 
is meaningless (characters can't be recognized and change the language 
setting still display black block characters). I am using Debian GNU/ Linux 
stretch/sid, kernel 4.0.0-2-rt-686-pae, and locale en_US.UTF-8
~~~~

**Comment by special** [comment]
Looks like an opengl/font issue. We've seen a couple of these, but ultimately they're intermittent Qt rendering problems. #367 should help solve a bunch of these problems, but there's not much else we can do on the Ricochet side.
