### ISSUE TITLE
Feature Request: Chat rooms

### ISSUE THREAD

**Issue by RobKohr** [ricochet-im/ricochet#412]
It would be great if you could create chat rooms that people could join.

**Comment by mkroman** [comment]
Similar request as #54 - unfortunately it's a very complex issue.

**Comment by scottprovost** [comment]
Building an anonymous gateway for anon chat is trivial and easily done. No reason for such a gateway to be specific to any one chat system. I can demo such a system if you like. No need for Ricochet to write anything special.
