### ISSUE TITLE
can't connect with a proxy connection 

### ISSUE THREAD

**Issue by icesquare** [ricochet-im/ricochet#416]
Tested with release 1.1.2 on Linux 

Steps to reproduce:
- Start ricochet with command line => OK 
- ricochet tries to setup a tor circuit => NOK because the internet connection request a proxy configuration 
- Open the the configuration window => OK 
- Try to apply the proxy configuration => NOK 

The application becomes very slow and didn't response for a while 
when I click on any parameter to configure it does the same 

Please note that when I configure the proxy manually in torrc I am able to connect without any issue 
![snapshoot_proxy_error](https://cloud.githubusercontent.com/assets/19433747/15366878/f65e351a-1d15-11e6-8caa-742a3349308b.jpeg)

**Comment by special** [comment]
I think your #417 and #418 cover all of the problems here more. The application issues you're talking about are probably related to the UI bug in #417, and the connection doesn't work due to the incorrect preference on #418.

I'll close this one in favor of those two bugs. Thanks!
