### ISSUE TITLE
Ui issue when trying to configure the proxy 

### ISSUE THREAD

**Issue by icesquare** [ricochet-im/ricochet#417]
Tested with release 1.1.2 on Linux

Steps to reproduce:
- Start ricochet with command line => OK 
- Click on configuration button to configure the proxy 
Then I have:
![snapshoot_proxy_error](https://cloud.githubusercontent.com/assets/19433747/15366981/75fab9e2-1d16-11e6-909b-2dafce73a149.jpeg)

**Comment by icesquare** [comment]
Similar issue when i success to apply a proxy configuration!:

![snapshoot_proxy_error2](https://cloud.githubusercontent.com/assets/19433747/15367131/3168755c-1d17-11e6-8ae8-90a072a498b8.jpeg)

**Comment by special** [comment]
Neat. I guess the resizing window animation messed up graphics here. We already disable that animation on Windows due to similar bugs; seems like we should just remove it entirely.

**Comment by icesquare** [comment]
If you have a patch or a dev branch I can test it.
BTW, I built a version with debug myself I will give it a try tomorrow and let you know if I have more traces

**Comment by icesquare** [comment]
Please note that I am not able to reproduce this issue on a version that I build myself on the same Linux machine the initial issue is gone, but I have an other display problem, see screenshot 
![ui_print](https://cloud.githubusercontent.com/assets/19433747/15424186/c624c84e-1e70-11e6-883e-0f390ffdf47e.jpeg)
![ui_print2](https://cloud.githubusercontent.com/assets/19433747/15424187/c62cc904-1e70-11e6-8436-04e62f76d7d1.jpeg)

When I refresh my screen by plug changing the resolution for example the problem is gone!

I don't know if it is the same issue or I need to create a new one

Regards,

**Comment by special** [comment]
That looks like the same issue, I'd say. Can you try the fix from #421?

**Comment by icesquare** [comment]
Fix #421  Tested OK on my setup
But I am facing a new issue with parsing an existing tor configuration I will create a separate issue for it.
You can merge this fix
Nice to have: To be tested on Mac OS too

**Comment by special** [comment]
I've tested for OS X. Merging that fix. Thanks.
