### ISSUE TITLE
Can't select https in proxy configuration 

### ISSUE THREAD

**Issue by icesquare** [ricochet-im/ricochet#418]
Tested with release 1.1.2 on Linux 

In proxy configuration it is not possible to select https this can cause problem for users connecting to tor via a network using a proxy 

when I select http I have this warning 

May 18 18:37:02.000 [notice] Bootstrapped 80%: Connecting to the Tor network
May 18 18:39:01.000 [warn] HTTPProxy configured, but no SOCKS proxy or HTTPS proxy configured. Watch out: this configuration will proxy unencrypted directory connections only.

Please note that when I configure the proxy manually in torrc I am able to connect without any issue #

**Comment by special** [comment]
Looks like we should be using HTTPSProxy instead of (in addition to?) HTTPProxy. How confusing.

**Comment by icesquare** [comment]
I make a fix for this issue:  #420 
https://github.com/ricochet-im/ricochet/pull/420/commits/7629b261ae6d91a7ead5e00df885caa8c6941471

Tested OK with and without proxy 

torrc is generated correctly now

**Comment by special** [comment]
Merged #420. Thanks!
