### ISSUE TITLE
Which tor.exe should I use when building for windows?

### ISSUE THREAD

**Issue by r04r** [ricochet-im/ricochet#423]
When building for windows, where should I get my tor.exe from? The size of the binary provided in the release does not seem the match the one from the tor expert bundle (https://www.torproject.org/dist/torbrowser/5.5.5/tor-win32-0.2.7.6.zip), and there's also the DLLs.

**Comment by rburchell** [comment]
https://github.com/ricochet-im/buildscripts/blob/master/mingw/build-deps.sh#L46 could be relevant.

**Comment by r04r** [comment]
Thanks!
