### ISSUE TITLE
Virus detection

### ISSUE THREAD

**Issue by jerefeltan** [ricochet-im/ricochet#424]
A famous antivirus, Kaspersky, detects the file `Ricochet-1.1.2.exe` like a virus. Recently, Kaspersky had a very low rate of false positives: `http://chart.av-comparatives.org/chart1.php`

`https://www.virustotal.com/en/file/d7b4604f7f42c8ab2aadbc2729e0453c117d07fb1d27744b4b7122073dc5e24d/analysis/1464301201/`

**Comment by special** [comment]
There's not much we can do about this, unfortunately. They're probably detecting some part of the tor binary.

I reported the installer as a false positive at https://newvirus.kaspersky.com/; hopefully that will help. Thanks for mentioning it.

**Comment by botherder** [comment]
Hello all. FWIW, I contacted Kaspersky and other AV vendors to request a verification and fix for this. I received an acknowledgement from Kaspersky and told me that the false positive has been fixed and should be resolved by the next update. Please, let me know if there are still similar FPs.

**Comment by special** [comment]
@botherder Thanks! The only major one left is mcafee; I just submitted it to their virus_research mail.

**Comment by botherder** [comment]
Any updates? If still isn't resolved I can try other routes.

**Comment by jerefeltan** [comment]
Today in virustotal, there is only 1 AV flagging it: **Emsisoft**.
https://www.virustotal.com/en/url/bdd2890ab990f05925f1e58ca73e0566ac8182b52020a131c4eb80dc274059db/analysis/1473805338/

**Comment by botherder** [comment]
The downloaded binary is still detected by more tho:
https://www.virustotal.com/en/file/d7b4604f7f42c8ab2aadbc2729e0453c117d07fb1d27744b4b7122073dc5e24d/analysis/1473702479/

**Comment by Hakarin** [comment]
detected by 5/57 on malwr 
https://malwr.com/analysis/MDYxZjE5OTUyZTMyNDRkZTgyYWU3OTQ5YTdkYWVhZWI/
