### ISSUE TITLE
link context menu items via right click do not work

### ISSUE THREAD

**Issue by kaizensoze** [ricochet-im/ricochet#429]

**Comment by gdrdrposteo** [comment]
From my experience when the cursor hovers over the link context menu it makes those menu items disappear and they don't come back even when the cursor isn't above it anymore. I am able to copy and paste links via the link context menu though AKA right clicking the link. You mean none of the link context menu items work for you? Even copy and pasting?

**Comment by kaizensoze** [comment]
If I left click a link, the context menu shows with available options. I pick copy and the link is pasted properly on paste. If I right click a link, the context menu shows with available options, but when I select copy and then go to paste, nothing is pasted because the link param passed to showContextMenu is empty/undefined.

**Comment by gdrdrposteo** [comment]
Hmm. I don't think I've experienced something like this? Do you mind we test this? Give me your ID? By the way, I'm just a lay person - but I think pretty familiar with Ricochet, how it works, etc. - but I'm willing to help. So it's up to you.

**Comment by kaizensoze** [comment]
I've already submitted a PR with a fix.

**Comment by gdrdrposteo** [comment]
Ah! Nice.
