### ISSUE TITLE
What tool can I use to translate a .ts file?

### ISSUE THREAD

**Issue by gdrdrposteo** [ricochet-im/ricochet#431]
I want to try to help translate Ricochet in my language. What tool can I use? Help please? Thanks!

**Comment by qsodev** [comment]
You should use Qt Linguist. It is part of Qt, but as far as I know also available as standalone application.
However the translation files are compiled into ricochet binary. So you have to rebuild the application to see your changes.

**Comment by gdrdrposteo** [comment]
Ah. Seems like a lengthy process. But I could see a preview of all of 
translations right? Before seeing what the translations look like on 
Ricochet (compiling and running).

**Comment by qsodev** [comment]
You can see and manipulate all translations in the linguist tool. It's possible to open all languages (.ts files) at once. Then you get all translations for a source text. Some texts have placeholders ( e.g. %1 ). These are replaced by the application with specific texts. For these you usually find a developer comment next to the source text to know where to place the %1 in your language translation.

**Comment by qsodev** [comment]
Maybe it is easier for you to use Transiflex like mentioned in the readme file. https://www.transifex.com/ricochet-im/ricochet/

**Comment by gdrdrposteo** [comment]
Hehe yeah Transifex is best for me ;)

**Comment by special** [comment]
Yep, transifex is the best solution. Let us know if there's any trouble.
