### ISSUE TITLE
What tests can I lay person like me do to make sure Ricochet does what it should?

### ISSUE THREAD

**Issue by gdrdrposteo** [ricochet-im/ricochet#432]

**Comment by special** [comment]
Hmm. Interesting question. What should it do? What things are you interested in testing?

Here are a few things you could test with a firewall or packet sniffer:

1. Ricochet should never make any network connections, other than over localhost to the `tor` instance
2. Ricochet should never listen for any network connections, other than over localhost for the `tor` instance
3. Any network observer should only see Tor traffic

Another good idea is to look in Ricochet's preferences, under the Tor tab, and see what Tor's log says. Some notices about failed connections are normal, and occasionally a warning about fetching descriptors having failed. You'd be looking for anything that says Tor isn't working properly.

I'm going to close this as not-a-bug, but feel free to comment for discussion.
