### ISSUE TITLE
Vanity Gen

### ISSUE THREAD

**Issue by ajay340** [ricochet-im/ricochet#435]
Is it possible to use a vanity gen like Garlic or Eshalot to generate a custom name?

**Comment by dmS0Zq** [comment]
Yes. Paste the private key for the hostname you want in `~/.local/share/Ricochet/ricochet/data-0/private_key`. You should probably do this when Ricochet isn't running.

**Comment by special** [comment]
Note that more recent versions of Ricochet/Tor might not have a 'data-0' folder anymore. In that case, the private key is stored in `ricochet.json`, as base64-encoded DER. Be sure to make a backup of that file before modifying it.
