### ISSUE TITLE
Compress, encrypt & verify both userdata & keys

### ISSUE THREAD

**Issue by makruz** [ricochet-im/ricochet#437]
Problem:
As it is, Ricochet does not encrypt users contact list or users encryption keys. Anyone who gets access to the Ricochet folders can read all users contact information and steal RSA keys, giving possibility to compromise communication in the future via man-in-the-middle-attacks.

Solution:
Compress, encrypt and verify both userdata and keys stored in Ricochet using AES-128-GCM, derived from user input passphrase via PBKDF2. Decrypt data to memory, only write encrypted data to hdd.

Mitigatin/temporary fix:
Store Ricochet files behind Veracrypt container etc. encrypted location.

**Comment by special** [comment]
Agreed. There's discussion on this in #33. There's nothing blocking encryption for the private key and contacts now, other than actually doing the work :)
