### ISSUE TITLE
ricochet 1.1.2 on windows 8.1 generates keys not accepted by osx version

### ISSUE THREAD

**Issue by hotelzululima** [ricochet-im/ricochet#439]
turns out the windows version of ricochet was generating a ricochet id ending in the digit '1'  .
. for some reason the OSX ricochet 1.1.2 on 10.10.5 version WONT accept a ricochet ID ending with the digit '1'.. ie 2-7 are ok but 8 9 0 are rejected also.. I am assuming its the checking for a proper ending for an id 
 but the  id  ricochet:2tfehvaxpfcjgmc1 was generated by an ricochet 1.1.2 install on a windows 8.1 system... and is not accepted on osx via manual  add or connection requests it seems

**Comment by hotelzululima** [comment]
ok just deleted ricochet and reinstalled it and got a key ending in 3 we will see how it  goes...

**Comment by hotelzululima** [comment]
can do connection request  from OSX to windows.. but when attempting to enter OSX generated address ricochet:gkt5hawe6adms5f3 on windows ricochet its rejected same code ending in 2,4,5,6,7 is accepted.. now I know why a friends attempt to use has been unsuccessful..

**Comment by hotelzululima** [comment]
ie the id generation routine seems to be failing in the first case...
and the id validation routine seems to be failing in the second case id ending  2-7 is valid check so 3 should pass muster

**Comment by hotelzululima** [comment]
havent been able to get a buildable instance of qt5.1+ installed yet under yosemite that passes muster with your code

**Comment by special** [comment]
> but the id ricochet:2tfehvaxpfcjgmc1 was generated by an ricochet 1.1.2 install on a windows 8.1 system... and is not accepted on osx via manual add or connection requests it seems

Contact IDs can never contain `1`. The character set is `a-z2-7` -- maybe it was an `l` instead?

> can do connection request from OSX to windows.. but when attempting to enter OSX generated address ricochet:gkt5hawe6adms5f3 on windows ricochet is rejected same code ending in 2,4,5,6,7 is accepted.. now I know why a friends attempt to use has been unsuccessful..

The validator also checks whether that ID is already one of your contacts, or is your own ID. It's supposed to display a popup if that happens, but this seems to be slightly broken. I bet that's what your seeing. To confirm, try changing an earlier character and then pasting it in with the 3 at the end.

**Comment by hotelzululima** [comment]
I was using virtual machines to test and cutting and pasting the address presented by your code from one to the other,, thats when all this occured.. no hand typing till trying to determine the nature of the bug..
I suggest this is NOT solved yet. :(
