### ISSUE TITLE
Cannot open on debian 8

### ISSUE THREAD

**Issue by ajay340** [ricochet-im/ricochet#440]
I downloaded the linux tar and extract it. When I clicked on ricochet, it said I there are no application installed for shared libraries.

**Comment by nogoegst** [comment]
Seems you're using GNOME 3. In order to run ELFs from Nautilus, see https://askubuntu.com/questions/286621/how-do-i-run-executable-scripts-in-nautilus.
It's intended to run from terminal emulator as written in README.

**Comment by special** [comment]
Sounds like a good explanation. Having a .desktop file for the portable package would be nifty (can they be relative?). See #352.
