### ISSUE TITLE
Ricochet 1.1.2 is flagged as malicious

### ISSUE THREAD

**Issue by gszathmari** [ricochet-im/ricochet#441]
According to the following VirusTotal report, the Windows installer is flagged as malicious for some reason:
https://virustotal.com/en/file/d7b4604f7f42c8ab2aadbc2729e0453c117d07fb1d27744b4b7122073dc5e24d/analysis/

It is a duplicate of #424, however the file is flagged as malicious by 7 different anti-malware products this time

**Comment by thiras** [comment]
I confirm that with latest Windows Defender. Latest Win7 x64

**Comment by special** [comment]
As mentioned in #424, these false positives have been resolved. Thanks.
