### ISSUE TITLE
Windows XP - Ricochet displays gibberish in windows/scren

### ISSUE THREAD

**Issue by sente2357** [ricochet-im/ricochet#454]
I know Windows XP is a old OS, however there are a lot of computers/users still using XP. Upon installing the program the program displays gibberish. See:

![ricochet b](https://cloud.githubusercontent.com/assets/14642513/18818678/33be9734-8345-11e6-89cd-8e2f7d2fb55c.jpg)

![ricochet a](https://cloud.githubusercontent.com/assets/14642513/18818682/3a2354b6-8345-11e6-9f2e-1555c29735c1.jpg)

**Comment by GitHubHatesTor** [comment]
What, are you connecting to the Internet with XP? You're already infected with something...
Why don't you use Windows 7, ReactOS, or Tails?

**Comment by special** [comment]
This is one of the rendering bugs that #367 should fix. The soon-to-be-released 1.1.4 includes that renderer by default for Windows.

I'm surprised it runs at all on Windows XP. No promises made there.
