### ISSUE TITLE
Add New options

### ISSUE THREAD

**Issue by GitHubHatesTor** [ricochet-im/ricochet#458]
Autostart when the user logged in
Check for updates on Startup
Autoaccept files(per user allow/disallow, default:disallow)

---
I am using qTox https://github.com/tux3/qTox
but since they stopped updating the core and it has "contact is offline even when they are online" bug
so I want to use ricochet.

**Comment by GitHubHatesTor** [comment]
pinging @tux3

**Comment by timkuijsten** [comment]
Like in most open source projects, time and resources are constrained, but a PR is always welcome.

**Comment by special** [comment]
> Autostart when the user logged in
#359

> Check for updates on Startup
#147 

> Autoaccept files(per user allow/disallow, default:disallow)
#15

Thanks!
