### ISSUE TITLE
adding project maintainer(s)?

### ISSUE THREAD

**Issue by kaizensoze** [ricochet-im/ricochet#459]
Given the issues/PRs piling up, I was just wondering if you'd be open to bringing a maintainer on board. I'd certainly be more than happy to volunteer myself.

**Comment by afk11** [comment]
Would be nice, special comes and goes. Since the project has it's own organization, it certainly should have people besides @special that can merge.

It certainly shouldn't be more ideal to people fork the repository and let this one go to waste. I'd love to see more people merging stuff here.

I think we're stuck though, because we need a maintainer who can merge sane looking PR's, and at least then we can spot others who might be interested.. And that's probably the ideal way for more active contributors to come about, but we need someone with commit access first!

**Comment by kaizensoze** [comment]
Right, I mean I realize it'd require trust in my competency and I've submitted at least one PR already that's been merged. But it's difficult to prove my competency when I have other PRs laying dormant that have yet to be merged/closed.

**Comment by afk11** [comment]
100% agree. I'd happily assist with code review and merging (I'm a big believer in a flat organization where people can come and go, but that means there's always one person). I wouldn't be up for leading development, but can review trivial/non-controvertial PR's.

**Comment by special** [comment]
Thanks for bringing this up. I'm sorry that I've been so inconsistently available as a maintainer this year -- for various reasons, it's been difficult to find the time and energy to keep up with this work. I need to find a way to do better here.

Any help that you want to offer is very appreciated! There's no need to have merge access before reviewing PRs, and those reviews are useful for everyone. I'm much more comfortable merging PRs that have already had other eyes and testing. I need to be very careful about granting commit access, but we can definitely improve the process.

Issue tracking and triage also uses up a lot of time and motivation. If you want to respond to bugs to answer questions, link duplicates, organize discussion and prioritize, etc, please do! GitHub doesn't allow labeling and closing bugs without also granting repository write permissions, but we can try to find a way to work that out for anyone making regular contributions..

I definitely need to work on getting PRs merged. What else can I do to enable you to help the project?

**Comment by kaizensoze** [comment]
Yeah I understand you not wanting to hand out commit access to someone without first assessing their sense of judgement. When I find a project of interest, I'll usually submit a fairly trivial pull request to test the waters and if it takes more than two weeks to get merged and/or acknowledged it's a disincentive to contributing to the project.

I imagine a lot of the existing issues are of the "does not install/start on x" variety. I'll take a look and see if there are any low hanging fruit without a pending pull request.

**Comment by rburchell** [comment]
Closing this as there isn't anything directly actionable here. I understand that there were (and perhaps still are) ongoing concerns here, but for the time being, there's not much that I can do about that.
