### ISSUE TITLE
Android client

### ISSUE THREAD

**Issue by bithurder** [ricochet-im/ricochet#460]
I see that TOR has a service runnable on Android.  Any particular reason there isn't an Android client for ricochet?  If it's just that nobody has taken the time, I'm wondering how easy it would be to take the open source Signal app and swap out the backend for ricochet.  However, I haven't check its license to see if that would be a restricted use.

**Comment by special** [comment]
There is discussion on an Android version under #115. There are unique challenges to Ricochet on mobile that will require some serious effort to solve, other than just UI porting.
