### ISSUE TITLE
UI: The screen font is small & not clear. Hard to read.

### ISSUE THREAD

**Issue by GitHubHatesTor** [ricochet-im/ricochet#464]
http://filenurse.com/download/169722459a57aaad77499622fbe13c43.html
Left: Ricochet, Right: qTox

Why Ricochet's UI is not clear enough to read?

**Comment by q6r** [comment]
I do QT_AUTO_SCREEN_SCALE_FACTOR=2 ricochet on linux, not sure how to do that on Windows.

**Comment by special** [comment]
This screenshot has expired. I suggest uploading images to github when posting comments so they stay here.

It's possible that the default font sizes aren't perfect. I particularly have doubts about the Windows logic there. If the entire UI is too small, it's likely a DPI scaling issue. Can you clarify which is the problem, and for which platform?

**Comment by GitHubHatesTor** [comment]
Sorry @special . Github simply won't allow me to upload a file to github!! (Javascript hater here)
The platform is Windows 7. Tested with multiple PCs, return same result.
Other apps never have this problem.

Left: Ricochet, Right: QtWeb(as sample)
http://filenurse.com/download/6db46f2999ce7bd495fc04c395c3f977.html

**Comment by special** [comment]
Wow, I see what you mean. For posterity, here is the screenshot:

![image](https://cloud.githubusercontent.com/assets/80188/20014608/46404a36-a27d-11e6-9e16-9632d5e7fddb.png)

This looks like bad text rendering/antialiasing to me. It definitely does not look like this for most Windows users.

Text rendering is changed significantly in the upcoming 1.1.4 release as part of #367. Let's see if problems continue after that update.

**Comment by GitHubHatesTor** [comment]
Thanks @special , v1.1.4 fixed this issue.
