### ISSUE TITLE
/usr/bin/lrelease file not found

### ISSUE THREAD

**Issue by cosmicpuppet** [ricochet-im/ricochet#465]
**Os:** Antergos x64

**When:** running make while building ricochet from source

**Error message:** it told me that `/usr/bin/lrelease` didn't exist.

**Solution:** I solved this by linking `/usr/bin/lrealease-qt4` to `/usr/bin/lrelease` and it works.

`ln -s /usr/bin/lrealease-qt4 /usr/bin/lrelease`

**Comment by rburchell** [comment]
Strange, given that "official" Qt does not call lrelease "lrelease-qt4". You may want to look into [qtchooser](http://manpages.ubuntu.com/manpages/wily/man1/qtchooser.1.html), which can be used to switch between different releases of Qt, if your distribution provides it.

As a sidenote, you won't be able to build (or run) ricochet against Qt 4. See the requirements in the [BUILDING documentation](https://github.com/ricochet-im/ricochet/blob/master/BUILDING.md).

**Comment by special** [comment]
Also note that `lrelease` is sometimes packaged separately in Qt5 distributions. It might be under a 'tools' package. It may still be called `lrelease-qt5` on your system, in which case using `qtchooser` is the right solution.
