### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by fate14** [ricochet-im/ricochet#466]
Is it possible to manually modify any of the bundled files to make the ricochet chat windows darker or invert the colors?

**Comment by GitHubHatesTor** [comment]
+1 because some people dislike white window(bright, hurt eye, etc).

**Comment by GitHubHatesTor** [comment]
Not complete dark, but something like this will be great:
https://github.com/tux3/qTox
Default theme: dark(grey)

**Comment by special** [comment]
Agreed. See #96 -- I'll leave a comment about implementation there also.
