### ISSUE TITLE
HTTP Proxy = HTTP+HTTPS

### ISSUE THREAD

**Issue by GitHubHatesTor** [ricochet-im/ricochet#467]
If I'm using HTTP Proxy such as Polipo/Privoxy, and I choose HTTP win Ricochet's proxy setting
Ricochet will stuck while connecting to Tor Network.

If the user select HTTP, Ricochet need to add these to torrc(both are required).

HTTPProxy  1.2.2.1:3
HTTPSProxy 1.2.2.1:3

**Comment by GitHubHatesTor** [comment]
P.S. My acquaintance emailed about this to john.brooks@dereferenced.net a month ago, got no reply about this.

**Comment by special** [comment]
This is fixed by 7629b261ae6d91a7ead5e00df885caa8c6941471 for the upcoming 1.1.4 release.

We actually want _only_ `HTTPSProxy`. The `HTTPProxy` setting is for non-tunneled directory requests, not CONNECT-style proxying. It shouldn't be necessary at all.

**Comment by GitHubHatesTor** [comment]
@special

This issue is closed, but I'll add some explanation here.

ReachableAddresses *:80,*:443
ReachableAddresses reject *:*

If you add port "80" like above, tor will make a connection directly to TorNODE:80/tcp.
Tor never use HTTP Proxy, until the user add "HTTPProxy x" to his torrc file.

If you use only "443", tor will use HTTPSProxy.

If the user specify "*:80,*:443", you should add HTTPProxy and HTTPSProxy.

Same bug is exist on Orbot:
https://trac.torproject.org/projects/tor/ticket/18751

**Comment by GitHubHatesTor** [comment]
^ somehow Github automatically removed asterisk...

**Comment by special** [comment]
That is indeed what Tor's documentation says, and it used to be true.

In modern Tor (actually for a few years now), clients never make unencrypted directory requests. All non-relay directory traffic is tunneled through tor's OR protocol and goes through ORPort instead. There is no code path where a non-relay can use HTTPProxy. The option should (and probably will) be deprecated, so I don't want to start using it. You're safe with HTTPSProxy, regardless of ReachableAddresses.

Sources:

https://gitweb.torproject.org/tor.git/tree/src/or/directory.c#n1242 -- this is the only path where HTTPProxy is used, along with `directory_send_command(... direct=1 ...)`, which is only called from here. Note that it's under `!use_begindir`.

https://gitweb.torproject.org/tor.git/tree/src/or/directory.c#n1030 -- non-relays must always use begindir

https://gitweb.torproject.org/tor.git/tree/src/or/directory.c#n1189 -- `!use_begindir` requests from non-relays trigger a BUG warning

https://trac.torproject.org/projects/tor/ticket/4724 Old Vidalia ticket discussing removal of HTTPProxy
