### ISSUE TITLE
Blank conversation window when receiving many new messages with Qt 5.7

### ISSUE THREAD

**Issue by special** [ricochet-im/ricochet#468]
Environment:
Qt 5.7, single window mode enabled
1. Make target conversation inactive
2. Receive lots of messages or very long messages, more than enough to fill the screen
3. Make conversation active

The view will be blank until scrolled or until another message is added. Then it will look normal.

This is a regression for #461.

**Comment by rburchell** [comment]
Are you sure you want to move to 5.7? Wouldn't it make more sense to stick with 5.6 LTS?

**Comment by special** [comment]
Hmm. There is no particular need for a LTS in Ricochet. I suppose it could potentially help avoid regressions like this one while still being able to update Qt.

We are particularly interested in the QtQuick 2D renderer, so having that functional is a priority.

Unclear if this bug also happens in 5.6, I have not tested.

**Comment by special** [comment]
Does not reproduce with Qt 5.6.2. Will take your advice and stick with 5.6 for now.
