### ISSUE TITLE
Add donation links to Ricochet resources

### ISSUE THREAD

**Issue by obvio171** [ricochet-im/ricochet#47]
What are the accepted ways of donating to the project? It would be good to make this more public. I want to make sure I can do something to keep this project alive, even if it's my insignificant 5 usd/month. I'm trying Gittip, but it's currently unclaimed: https://www.gittip.com/on/github/ricochet-im/. Thanks!

**Comment by special** [comment]
Repurposing this to add the invisible.im links into some places around Ricochet's documents, to verify that they're legitimate.

But, I still think people should donate to Tor.
