### ISSUE TITLE
Does Ricochet encrypt message(conversation)/files?

### ISSUE THREAD

**Issue by GitHubHatesTor** [ricochet-im/ricochet#470]
Does Ricochet encrypt/decrypt conversation? (text+ files send/receive)
If so, what algorithm are you using?
If not, why not encrypt the data before sending?

**Comment by clintidau** [comment]
Ricochet messages use the end-to-end encryption that is built in to Tor's hidden service protocol.
Discussion: https://github.com/ricochet-im/ricochet/issues/72
