### ISSUE TITLE
Ricochet + HTTP Proxy

### ISSUE THREAD

**Issue by GitHubHatesTor** [ricochet-im/ricochet#478]
1. config
Proxy Type: select HTTP.
Address and Port: fill.
Allowed Ports: "443" only

2. Connect.

[warn] HTTPProxy configured, but no SOCKS proxy or HTTPS proxy configured. Watch out: this configuration will proxy unencrypted directory connections only.

Tor makes a direct connection to :443/tcp, not using HTTP Proxy.

3. Ricochet's torrc file shows:

ControlPort auto
DisableNetwork 0
FascistFirewall 1
FirewallPorts 443
HiddenServiceStatistics 0
HTTPProxy XXXXXXX
Log notice stdout
ReachableAddresses *:443
ReachableAddresses reject *:*

This is a mistake because if the user choose port 443, tor will use "HTTPSProxy", not "HTTPProxy".

**Comment by GitHubHatesTor** [comment]
Also, you don't need "FirewallPorts". Only ReachableAddresses is enough to achieve port limit.

ReachableAddresses *:443 = HTTPSProxy only
ReachableAddresses *:80,*:443 = require HTTPProxy and HTTPSP.
ReachableAddresses *:80 = HTTPProxy only.

**Comment by special** [comment]
HTTPProxy is never used by a modern Tor client. HTTPSProxy will be used for all connections. See my explanation at https://github.com/ricochet-im/ricochet/issues/467#issuecomment-258484978

**Comment by GitHubHatesTor** [comment]
@special
I deleted Ricochet:s torrc file, and done Step 1 and 2. Ricochet automatically creates torrc file.

ControlPort auto
DisableNetwork 0
FascistFirewall 1
FirewallPorts 443
HiddenServiceStatistics 0
HTTPProxy XXXXXXX ###this
Log notice stdout
ReachableAddresses *:443
ReachableAddresses reject :

I'm using latest Ricochet on Windows. See, Ricochet is using "HTTPProxy", not "HTTPSProxy".

> HTTPProxy is never used by a modern Tor client

No, HTTPProxy is still being used by Tor client.
If the user add port 80, Tor will use HTTPP. If not(like 443), HTTPSP.

Try HTTP Proxy(Polipo, Privoxy, whatever) with tor.

**Comment by GitHubHatesTor** [comment]
It seems I'm wrong about something. (I stopped adding port 80 to "allow list", so I don't use HTTPProxy anyway.)

1. Delete Ricochet's torrc file.
2. "Allowed Ports": "80"
3. Connet

Tor connected to Tornodes:80/tcp directly.

**Comment by special** [comment]
@GitHubHatesTor Ricochet 1.1.2 set HTTPProxy instead of HTTPSProxy. That was a bug, but it is fixed in git master and 1.1.4 -- which I'm working on releasing _right now_.

**Comment by GitHubHatesTor** [comment]
https://trac.torproject.org/projects/tor/ticket/2057


It seems I'm wrong about something. (I stopped adding port 80 to "allow list", so I don't use HTTPProxy anyway.)

    Delete Ricochet's torrc file.
    "Allowed Ports": "80"
    Connet

Tor connected to Tornodes:80/tcp directly.

**Comment by GitHubHatesTor** [comment]
https://trac.torproject.org/projects/tor/ticket/20575

It seems I'm wrong about something. (I stopped adding port 80 to "allow list", so I don't use HTTPProxy anyway.)

Delete Ricochet's torrc file.
"Allowed Ports": "80"
Connet

Tor connected to Tornodes:80/tcp directly.
