### ISSUE TITLE
Minimizing to tray, file transfer, automatic updates and bridge support

### ISSUE THREAD

**Issue by throwaway000** [ricochet-im/ricochet#479]
I'm sorry, but it's an instant messaging software. Ability to minimize to tray is a must. Also, file transfer would be great improvement. TorChat allows you to transfer files, Ricochet does not.

Also, I don't think that automatic updates would compromise the security here. After all, Tor Browser has that implemented. Of course, the connection would have to go through tor.

And lastly, Tor Browser allows you to select bridges as well as other similar connection options automatically. It would be great to have it in Ricochet as well.

**Comment by GitHubHatesTor** [comment]
https://github.com/ricochet-im/ricochet/issues/364
https://github.com/ricochet-im/ricochet/pull/262
https://github.com/ricochet-im/ricochet/pull/260

https://github.com/ricochet-im/ricochet/issues/147

Change the title to "file transfer" and "bridge support" only.

**Comment by gianni76** [comment]
I fully support the request for the file transfer functionality. 
This is essential in any real-world situation with field-deployed personnel. I have been waiting this (relatively simple) addition over two years and had to abandon ricochet due to this precise point.
Hope it will come sooner or later...

**Comment by special** [comment]
See also #65 and #66 about bridge support.

I agree that these are all important things to get done. This is all volunteer effort, so it does take time. Thanks for being patient.
