### ISSUE TITLE
1.1.4: Ricochet add multiple line to /config/tor/torrc file

### ISSUE THREAD

**Issue by GitHubHatesTor** [ricochet-im/ricochet#482]
Ricochet's torrc file:

ControlPort auto
DisableNetwork 0
FascistFirewall 1
FirewallPorts 443
HiddenServiceStatistics 0
HTTPProxy XXX
HTTPSProxy XXX
Log notice stdout
ReachableAddresses *:80
ReachableAddresses reject *:*
ReachableAddresses reject *:*
ReachableAddresses reject *:*
ReachableAddresses reject *:*
ReachableAddresses reject *:*
ReachableAddresses reject *:*
ReachableAddresses reject *:*
ReachableAddresses reject *:*
ReachableAddresses reject *:*
ReachableAddresses reject *:*
ReachableAddresses reject *:*

1. Why Ricochet add too many "reject" lines?
2. Why Ricochet add "*:80"? I only input 443 to allowed port.

**Comment by GitHubHatesTor** [comment]
If the user change connection configuration, make a fresh torrc file(delete or overwrite old one).

**Comment by special** [comment]
Hmm. I wonder why Tor repeats it. To reproduce:

1. Set a reachable ports restriction for tor and let it connect
2. Reconfigure tor to connect directly

I think the fix is that we should be setting ReachableAddresses instead of FascistPorts, and we need to include ReachableAddresses in the RESETCONF when connecting directly.

**Comment by special** [comment]
This fixes the behavior problem, but there's still a spurious warning from tor:

```
Dec 03 14:48:06.000 [warn] Tor cannot connect to the Internet if ReachableAddresses, ReachableORAddresses, or ReachableDirAddresses reject all addresses. Please accept some addresses in these options.
```

And additional ReachableAddresses lines are still added to the torrc. These are bugs in tor. The option will still work correctly.

**Comment by GitHubHatesTor** [comment]
> And additional ReachableAddresses lines are still added to the torrc. These are bugs in tor. 

No it's not a bug of Tor. Tor don't edit a "torrc" file itself.

**Comment by special** [comment]
> > And additional ReachableAddresses lines are still added to the torrc. These are bugs in tor.
> No it's not a bug of Tor. Tor don't edit a "torrc" file itself.

https://trac.torproject.org/projects/tor/ticket/20874
https://trac.torproject.org/projects/tor/ticket/20306

Tor does modify the torrc if a controller issues SAVECONF or, as Ricochet does, retrieves the current effective config with GETINFO config/text and saves it.
