### ISSUE TITLE
Large amount of RAM used

### ISSUE THREAD

**Issue by inDane** [ricochet-im/ricochet#483]
it uses up to 1,1gb ram (as far as i can tell) . And has a 20TB VSZ
~$ uname -a
Linux xx 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

~$ ps -aux | grep ricochet
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
xx       6198  1.8 20.4 21475522380 826960 ?  Sl   19:51   0:05 ricochet

**Comment by special** [comment]
What version of ricochet? Did you compile yourself, use our linux binaries, or install a package?

What you're seeing here is [ASAN](http://clang.llvm.org/docs/AddressSanitizer.html). It was enabled by default for 1.1.2, but ultimately had too much of a runtime impact (like what you're seeing here). ASAN should not be enabled by default for non-debug builds of Ricochet 1.1.4.

I suggest upgrading to 1.1.4.

**Comment by inDane** [comment]
its version 1.1.2
i've installed it via the ubuntu reposity

apt-get -s install ricochet-im 
NOTE: This is only a simulation!
      apt-get needs root privileges for real execution.
      Keep also in mind that locking is deactivated,
      so don't depend on the relevance to the real current situation!
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ricochet-im is already the newest version (1.1.2-1).

i will upgrade it manually, thanks!

**Comment by inDane** [comment]
yup, as you said, the new version is not that memory hungry!
