### ISSUE TITLE
Change fonts

### ISSUE THREAD

**Issue by jpt** [ricochet-im/ricochet#485]
I have created a wiki page for a [Visual Style Guide](https://github.com/ricochet-im/ricochet/wiki/Visual-Style-Guide) -- I find style guides helpful for keeping track of these sorts of decisions around fonts and so on. 

In that guide I am suggesting the use of [Rubik](https://www.fontsquirrel.com/fonts/rubik) and [Liberation Sans](https://www.fontsquirrel.com/fonts/liberation-sans). Both are free, open source projects released under the [SIL Open Font License](http://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web). For reference, these are the fonts as used in the mockups in #484.

Liberation Sans is essentially Helvetica. Helvetica is proprietary font software, so Red Hat commissioned a free one. Regarding the use of Liberation Sans, I trust Apple's data on usability and legibility of this font (up until the past couple years, iOS and macOS used Helvetica -- they now use San Francisco, a similar derivative), but I also just happen to like Helvetica 😃 

Rubik is a geometric neo-grotesque that looks good in both all-caps and in title case, which I think makes it ideal for interfaces. Its slightly rounded corners and geometry tend to evoke of a small amount of NASA-like retro-futurism, but its strict grid keeps it very legible and prevents it from getting too playful. That could be a nice mix for our technical crowd.

As on the wiki, I am suggesting the following uses:

* **Interface headings:** Rubik Medium
* **Interface text:** Rubik Regular
* **Speech bubbles:** Liberation Sans Regular

Considerations: ricochet.im already uses different fonts, and consistency will help in branding a product at this stage, so maybe fonts are too fine-grain for right now and we need to zoom out and look at the brand as a whole first. Also, my opinion for using Liberation Sans Regular for the messages in the speech bubbles is much stronger than my opinion RE: Rubik, even though I'm fond of it.

In any case, things like font choices may seem a bit premature when more technical stuff like file transfers, Tails compatibility, etc, still need figuring out, but my experience has been that making things "pretty" early really helps with user adoption, which helps bring in contributors.

**Comment by special** [comment]
This isn't premature at all. Fonts are an easy change to make with a massive visual and usability impact. We've had issues with legibility and font sizes on various platforms already.

We're currently using whatever OS default interface font Qt picks up, at sizes based on the default platform font size. It seems to me like text is pretty small on Windows, about right on OS X, and could be literally anything on Linux. I'm open to not using the defaults if we pick something that looks good, is readable, and doesn't stand out as being "wrong" to users.

There are potential accessibility concerns if we ignore the system font sizes. I think all of these platforms support scaling up fonts for readability. I bet that breaks Ricochet in other ways now, though, and it should be a solvable problem.

The mockups look very nice. I'm not entirely convinced on Rubik (those J's!), but I'd want to see how it feels in action. It is a little more interesting and unique, which I do like.

> I have created a wiki page for a Visual Style Guide -- I find style guides helpful for keeping track of these sorts of decisions around fonts and so on.

❤️

> Considerations: ricochet.im already uses different fonts, and consistency will help in branding a product at this stage

The story of ricochet.im is thus: I hacked up a template until it was more or less acceptable, and I reaffirmed my life choices re: not doing webdev. All things are subject to change given motivation. Fonts are probably easy to swap, in particular. The whole website is at https://github.com/ricochet-im/website/ if you're curious (or if someone is motivated!)

**Comment by jpt** [comment]
Glad you don't think fonts are too early to consider!

> There are potential accessibility concerns if we ignore the system font sizes. I think all of these platforms support scaling up fonts for readability. I bet that breaks Ricochet in other ways now, though, and it should be a solvable problem.

Hmm, true. Well, for starters, I'll start documenting font sizes in em units or percentages so they can at least be documented relative to themselves, relative to the system default.

For accessibility I like the idea of using system font sizes as a _basis_ for enhancing the experience, not just for uniformly increasing its size. Accessibility is a requirement, but what I don't want to do is end up with a bunch of line-breaks, hyphenation and cluttered UI in the name of inflatable type, because a screen magnifier would be a more reasonable solution at that point. So it may take some time to think of good solutions. For example, if a contact name on the left becomes too long for width of the contact list window, maybe fade it out the contact name on the right before it reaches the edge, and give it a marquee effect on hover to reveal the whole name, etc. That level of accessibility design might require an expert, though, so let's also think about where the compromises lie during development, because that's also a reality given resources. I would love to know if "works on the system magnifier" is a actually an acceptable solution (during development) to those who would use it

> The mockups look very nice. I'm not entirely convinced on Rubik (those J's!), but I'd want to see how it feels in action. It is a little more interesting and unique, which I do like.

If we do end up with a font that is fine except for the odd letter or two, I'm no stranger to a font editor 😃 At this early phase of design, what I like to do when still playing with fonts is just swap them out in the mockups a lot, so we don't grow too attached to any. Ideally I'd also want something a little less distinct than Rubik, I agree, but there is a lack of libre Proxima Nova style fonts in multiple weights... a font where the H is farly square, without making the lowercase too round, I find those work very well for interfaces. Pablo Impallari's "Cabin" is one that I like a lot but the bold isn't bold enough, and it's just a little twee for my taste. Still, may try that one next. Montserrat is way too round and wide, and too art deco at lighter weights. Fira might be a consideration. I'd prefer to avoid Roboto and Open Sans. 

I'm happy to make changes to the website once we've actually figured out the fonts.

**Comment by jpt** [comment]
I'm seriously reconsidering Open Sans as a Rubik replacement (still Liberation Sans for message body). Just can't use it in all-caps. 
![image](https://cloud.githubusercontent.com/assets/5319916/20912814/650c2878-bb27-11e6-85f1-bdd12c64054e.png)

**Comment by jpt** [comment]
Let's consider this one closed: 

Interfaces: Open Sans
Speech Bubbles: Liberation Sans
Titles: Open Sans

I would recommend an entirely different set of fonts for the website, but I'll get to that when I get to that. 

Interface headings: Open Sans Semibold
Interface text: Open Sans Regular
Speech bubbles: Liberation Sans Regular

Sorry, Rubik, I almost liked you.

We can reconsider type choices for web and logo and branding and stuff like that when it makes sense.
