### ISSUE TITLE
Error on installation "Cannot create directory ..."

### ISSUE THREAD

**Issue by robotme** [ricochet-im/ricochet#491]
Cannot create directory: /private/var/folders/yd/x6hyxwdn5pd76ss_znft2dwm0000gn/T/AppTranslocation/51963695-B778-49FC-8179-BB180E53F964/d/config.ricochet

Are other people experiencing this? 

MacOS 10.12.2

Sorry if this is the wrong place to ask. I don't know where else to ask troubleshooting questions for most open source applications found on GitHub.

**Comment by special** [comment]
We really need to get this one fixed.

You need to drag Ricochet out of the .dmg to a location of your choice (such as the Applications folder) before running it. This error is trying, very badly, to say that you can't run from inside a disk image.

See #122
