### ISSUE TITLE
[Idea] Ricochet without Tor

### ISSUE THREAD

**Issue by GitHubHatesTor** [ricochet-im/ricochet#492]
Usage:
I have a website aaaaaaaaaaaaaaa.onion.
I want to use "Ricochet:aaaaaaaaaaaaaaaaa".
I changed torrc file like this: so Ricochet can receive/send a message.

RicochetListenport(localhost:9009) <---> Tor Hidden Service <---> Tor users

Why Ricochet have to use Controlport?
To make a new onion address, just start tor in background and read /folder/onionname to get the address.
To stop tor, just 'kill tor'.
To check other user(ricochet:otheruseridhere), send a request to http://ricochet.otheruseridhere.onion/test.txt and see if it returns http 200.
etc etc.

**Comment by GitHubHatesTor** [comment]
X Ricochet without Tor
O Ricochet server-only mode(use foreign Tor SOCKS proxy only)

**Comment by special** [comment]
> Why Ricochet have to use Controlport?

Ricochet uses the control port to configure bundled tor, monitor tor's connection state, and dynamically publish services. Even when not using bundled tor, these last two are important to its basic functionality. Also, for unbundled tor, the control port is even more important to allow configuring services without filesystem permissions problems.

It's expected that Ricochet will be using the control port to more aggressively monitor connectivity and to publish additional hidden services dynamically. Having access to the control port isn't and will not be optional.

> I have a website aaaaaaaaaaaaaaa.onion.
> I want to use "Ricochet:aaaaaaaaaaaaaaaaa".

My suggestion would be to publish a normal ricochet address on the website. There is a `"tor": { "neverPublishServices": true }` option, but it's meant for development only and still requires the control port and exposing the private key to Ricochet.

In general, supporting unusual cases like these would tie our hands for future development. Saying "no" now means we don't have to break functionality people are relying on in the future.
