### ISSUE TITLE
Request: ricochet-cli

### ISSUE THREAD

**Issue by cybershambles** [ricochet-im/ricochet#497]
QT gives me the fear. I'd love something I can use on the commandline for my daily communication

or even a headless ricochet-cli api that responsed with json and I could code a frontend on multiple different frameworks.

**Comment by wfr** [comment]
You can consider my fork of Ricochet that implements an IRC server.
https://github.com/wfr/ricochet-irc/blob/irc/README-irc.md

**Comment by special** [comment]
I've spent some time quietly writing an experimental split-process Ricochet client in Go. The first frontend for it is a readline-style CLI (also in Go).

https://github.com/ricochet-im/ricochet-go

This isn't fully functional yet (e.g. no contact requests), and it's definitely not safe to use, but it will be. If you're interested in helping out on that project or writing other frontends, get in touch. I've been staying fairly quiet about it until it's ready for alpha-level users.

---

@wfr that is genuinely insane -- I'm impressed.
