### ISSUE TITLE
Multiple Ricochet account

### ISSUE THREAD

**Issue by GitHubHatesTor** [ricochet-im/ricochet#498]
It'll be nice if I can have multiple account, with the ability of removing/creating a new one.
Single Tor instance can host multiple hidden service, why not use it?

Possible attack

Reallife U: Friend B, I have ricochet:aaaaaa (= aaaaaa.onion)
Hidden U(using TBB): Forum user C, I have ricochet:aaaaaa

C: "Hey, you're U, right?"
U: "...WTF!?"

**Comment by mkroman** [comment]
See also #381, #235 and #99.

**Comment by special** [comment]
Also #304. Quite a bit of discussion on the topic in those bugs. For now, the solution is to run more than one Ricochet.

My main concern would be designing the user experience to keep identities and contacts clearly separate, and as much as possible prevent accidental contamination across them. It's a tricky design problem.

There is also a risk of making correlation attacks easy when all of your identities come online and go offline at the same time.
