### ISSUE TITLE
[PR] Advertise Ricochet to "Tor at Heart"

### ISSUE THREAD

**Issue by GitHubHatesTor** [ricochet-im/ricochet#499]
e.g.,
1. https://blog.torproject.org/blog/tor-heart-onionshare
2. "This is the first time I heard about"
3. More people use Ricochet.

MAKE RICOCHET GREAT AGAIN!!

**Comment by chovy** [comment]
MAKE TOR GREAT AGAIN

**Comment by special** [comment]
I saw that one of the blog posts had a section on Ricochet. As far as I know Ricochet won't be involved in "Tor at Heart" beyond that.
