### ISSUE TITLE
Stop Ricochet from Popping in front of windows

### ISSUE THREAD

**Issue by BlazingInferno** [ricochet-im/ricochet#506]
It would be great if there was an way to stop Ricochet from appearing when I get an message and for example taking me out of cs:go.

**Comment by special** [comment]
That sounds annoying.

I suggest turning on "single window for conversations" in preferences to stop new windows from popping up. That option is the default now, and the multiple window mode might even be removed in the future.

**Comment by githubbantor** [comment]
@special

How about adding a new option: "[X] Don't show window to top when first message arrived"?
The user can still hear the notification sound(if set).

; actually, I'm waiting for "close|minimize to tray" option

**Comment by BlazingInferno** [comment]
@special that option does nothing for the popups from new messages. I support what @githubbantor said about having the option for "Don't show window to top when first message arrived" also the "minimize to tray" option.
