### ISSUE TITLE
Start Ricochet on system start-up

### ISSUE THREAD

**Issue by obvio171** [ricochet-im/ricochet#51]
Helps get to critical mass. It's been easy getting people to install and use Ricochet the first time, but they often don't have immediate reason to open it and quickly forget about it.

**Comment by special** [comment]
Would be helpful to figure out and write down the correct way to do this on relevant platforms. Any takers?

**Comment by special** [comment]
Oh hey, apparently I did most of that, a long time ago.

Closing this in favor of the duplicate #359, because it has some details on implementation. Thanks!
