### ISSUE TITLE
UX: Package DMG with an "Applications" folder alias and a background (OSX)

### ISSUE THREAD

**Issue by jpt** [ricochet-im/ricochet#510]
I had a friend ask about the error when double-clicking the Ricochet application from within mounted DMG. 

Something not unlike this.

(no reason for this particular image, first google image result)

![install](http://www.luxrender.net/wiki/images/d/dc/OSX_luxrender_install.png) 

An even better solution that I've seen on modern Mac apps is double-click opens, and then asks if you want to move the app to the Applications folder, but that may be a lot more work.

**Comment by special** [comment]
Definitely agree. See #122 for more discussion around this. I believe it's easy to include a background like this, if we had one.
