### ISSUE TITLE
EntryNodes and ExcludeNodes

### ISSUE THREAD

**Issue by allpingers** [ricochet-im/ricochet#519]
Why is ricochet removing EntryNodes and ExcludeNodes that are entered into the torrc file?  These are valid entries that people in the know might want in there.

**Comment by special** [comment]
Be certain that Ricochet isn't running if you edit the torrc file manually. Are the options still disappearing if you edit it while Ricochet is shut down? Is there anything near the beginning of the Tor log in preferences about these options?

**Comment by allpingers** [comment]
It is working now - thanks.
