### ISSUE TITLE
Apparmor Profile

### ISSUE THREAD

**Issue by 0xREX** [ricochet-im/ricochet#534]
Ricochet seems to open and function without breaking with the below apparmor profile. Should I be concerned about any of the files I have labelled `deny`? And why are `machine-id` and `uuid` needed? I'm clearly not a developer. If you tell me machine-id (or anything currently denied) is essential to funtionality, I'll certainly allow it.

	#include <tunables/global>

	/ricochet/ricochet {
	  #include <abstractions/base>

	  deny /dev/tty r,
	  deny /etc/ld.so.preload r,
	  deny /etc/udev/udev.conf r,
	  deny /home/username/.Xauthority r,
	  deny /proc/meminfo r,
	  deny /sys/devices/system/cpu/ r,
	  deny /var/lib/dbus/machine-id r,
	  deny /home/username/.cache/* r,
	  deny /proc/sys/kernel/random/uuid r,

	  /dev/dri/card0 rw,
	  /etc/drirc r,
	  /etc/fonts/** r,
	  /ricochet/QtQuick.2/* r,
	  /ricochet/QtQuick/Controls/* r,
	  /ricochet/QtQuick/Dialogs/* r,
	  /ricochet/QtQuick/Layouts/* r,
	  /ricochet/QtQuick/PrivateWidgets/* r,
	  /ricochet/QtQuick/Window.2/* r,
	  /ricochet/config/ w,
	  /ricochet/config/* rwk,
	  /ricochet/config/tor/ rw,
	  /ricochet/config/tor/* rw,
	  /ricochet/config/tor/lock rwk,
	  /ricochet/ricochet mr,
	  /ricochet/tor mrix,
	  /run/udev/data/\+pci:0000:00:02.0 r,
	  /sys/devices/pci0000:00/0000:00:02.0/uevent r,
	  /usr/lib{,32,64}/** mr,
	  /usr/local/share/fonts/ r,
	  /usr/share/fontconfig/conf.avail/90-fonts-nanum.conf r,
	  /usr/share/fonts/ r,
	  /usr/share/fonts/** r,
	  /usr/share/icons/DMZ-Black/cursor.theme r,
	  /usr/share/icons/DMZ-Black/index.theme r,
	  /usr/share/icons/whiteglass/cursors/* r,
	  /usr/share/poppler/cMap/*/ r,
	  /var/cache/fontconfig/* r,
	  /usr/share/tor/geoip r,
	  /usr/share/tor/geoip6 r,
	}

Many thanks.

**Comment by qbi** [comment]
Recntly there was a question at https://tor.stackexchange.com regarding a AppArmor profile for Ricochet: https://tor.stackexchange.com/q/14463/88

**Comment by rburchell** [comment]
machine-id and uuid are likely needed from an indirect dependency, my guess would be a plugin using DBus (for instance, the QtNetwork bearer plugins on Linux that talk to connman/NetworkManager for network state information).

There's already another bug open about packaging a profile at #400, so I think this can be closed.
