### ISSUE TITLE
Split code into core library and GUI

### ISSUE THREAD

**Issue by aelmahmoudy** [ricochet-im/ricochet#540]
I syggest splitting the code into core library implementing the protocol and connectivity, and GUI. Additionally the core library not to use QT library. The rationalle is to make ricochet portable to other systems that are not well supported by QT, such as Android.

**Comment by rburchell** [comment]
There has been some experimentation in this area, but portability is not the underlying driver here. See https://github.com/ricochet-im/ricochet-go for more information.

Qt should work OK on Android, but none of the core team have any bandwidth for working on a mobile client at this time that I am aware of, see #115.
