### ISSUE TITLE
1.1.4 compile error on freebsd

### ISSUE THREAD

**Issue by zhou0** [ricochet-im/ricochet#548]
g++ -m64 -fPIC -fstack-protector-strong -pie -Wl,-z,relro,-z,now -Wl,-O1 -Wl,-rpath,/usr/local/lib -o ricochet release/main.o release/MainWindow.o release/ContactsModel.o release/TorControl.o release/TorControlSocket.o release/TorControlCommand.o release/ProtocolInfoCommand.o release/AuthenticateCommand.o release/SetConfCommand.o release/AddOnionCommand.o release/StringUtil.o release/ContactsManager.o release/ContactUser.o release/GetConfCommand.o release/HiddenService.o release/CryptoKey.o release/SecureRNG.o release/OutgoingContactRequest.o release/IncomingRequestManager.o release/ContactIDValidator.o release/UserIdentity.o release/IdentityManager.o release/ConversationModel.o release/TorProcess.o release/TorManager.o release/TorSocket.o release/LinkedText.o release/Settings.o release/PendingOperation.o release/LanguagesModel.o release/Channel.o release/ControlChannel.o release/Connection.o release/OutboundConnector.o release/AuthHiddenServiceChannel.o release/ChatChannel.o release/ContactRequestChannel.o release/ControlChannel.pb.o release/AuthHiddenService.pb.o release/ChatChannel.pb.o release/ContactRequestChannel.pb.o release/qrc_qml.o release/qrc_icons.o release/qrc_sounds.o release/qrc_embedded.o release/moc_MainWindow.o release/moc_ContactsModel.o release/moc_TorControl.o release/moc_TorControlSocket.o release/moc_TorControlCommand.o release/moc_ProtocolInfoCommand.o release/moc_AuthenticateCommand.o release/moc_SetConfCommand.o release/moc_AddOnionCommand.o release/moc_ContactsManager.o release/moc_ContactUser.o release/moc_GetConfCommand.o release/moc_HiddenService.o release/moc_OutgoingContactRequest.o release/moc_IncomingRequestManager.o release/moc_ContactIDValidator.o release/moc_UserIdentity.o release/moc_IdentityManager.o release/moc_ConversationModel.o release/moc_TorProcess.o release/moc_TorProcess_p.o release/moc_TorManager.o release/moc_TorSocket.o release/moc_LinkedText.o release/moc_Settings.o release/moc_PendingOperation.o release/moc_LanguagesModel.o release/moc_Channel.o release/moc_Channel_p.o release/moc_ControlChannel.o release/moc_Connection.o release/moc_Connection_p.o release/moc_OutboundConnector.o release/moc_AuthHiddenServiceChannel.o release/moc_ChatChannel.o release/moc_ContactRequestChannel.o   -L/usr/X11R6/lib64 -L/usr/local/lib -lcrypto -lprotobuf -D_THREAD_SAFE -pthread -lQt5Quick -lQt5Widgets -lQt5Multimedia -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
release/AuthHiddenServiceChannel.o: In function `Protocol::AuthHiddenServiceChannel::processChannelOpenResult(Protocol::Data::Control::ChannelResult const*)':
AuthHiddenServiceChannel.cpp:(.text+0x574): 未定義參考到「google::protobuf::internal::ExtensionSet::GetString(int, std::string const&) const」
release/AuthHiddenServiceChannel.o: In function `Protocol::AuthHiddenServiceChannel::allowInboundChannelRequest(Protocol::Data::Control::OpenChannel const*, Protocol::Data::Control::ChannelResult*)':
AuthHiddenServiceChannel.cpp:(.text+0xc2e): 未定義參考到「google::protobuf::internal::ExtensionSet::GetString(int, std::string const&) const」
release/ControlChannel.pb.o: In function `Protocol::Data::Control::OpenChannel::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
ControlChannel.pb.cc:(.text+0x4a0): 未定義參考到「google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)」
release/ControlChannel.pb.o: In function `void google::protobuf::internal::RepeatedPtrFieldBase::Destroy<google::protobuf::RepeatedPtrField<std::string>::TypeHandler>() [clone .isra.56]':
ControlChannel.pb.cc:(.text+0x6cb): 未定義參考到「google::protobuf::internal::StringTypeHandlerBase::Delete(std::string*)」
release/ControlChannel.pb.o: In function `Protocol::Data::Control::OpenChannel::SerializeWithCachedSizesToArray(unsigned char*) const':
ControlChannel.pb.cc:(.text+0xde8): 未定義參考到「google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)」
release/ControlChannel.pb.o: In function `Protocol::Data::Control::OpenChannel::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)':
ControlChannel.pb.cc:(.text+0x13f2): 未定義參考到「google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)」
release/ControlChannel.pb.o: In function `Protocol::Data::Control::FeaturesEnabled::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
ControlChannel.pb.cc:(.text+0x1a64): 未定義參考到「google::protobuf::internal::WireFormatLite::WriteString(int, std::string const&, google::protobuf::io::CodedOutputStream*)」
release/ControlChannel.pb.o: In function `Protocol::Data::Control::EnableFeatures::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
ControlChannel.pb.cc:(.text+0x1dd4): 未定義參考到「google::protobuf::internal::WireFormatLite::WriteString(int, std::string const&, google::protobuf::io::CodedOutputStream*)」
release/ControlChannel.pb.o: In function `Protocol::Data::Control::EnableFeatures::SerializeWithCachedSizesToArray(unsigned char*) const':
ControlChannel.pb.cc:(.text+0x2145): 未定義參考到「google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)」
release/ControlChannel.pb.o: In function `Protocol::Data::Control::FeaturesEnabled::SerializeWithCachedSizesToArray(unsigned char*) const':
ControlChannel.pb.cc:(.text+0x24c5): 未定義參考到「google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)」
release/ControlChannel.pb.o: In function `Protocol::Data::Control::EnableFeatures::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)':
ControlChannel.pb.cc:(.text+0x2afb): 未定義參考到「google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)」
ControlChannel.pb.cc:(.text+0x2b8e): 未定義參考到「google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)」
release/ControlChannel.pb.o: In function `Protocol::Data::Control::FeaturesEnabled::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)':
ControlChannel.pb.cc:(.text+0x2f0b): 未定義參考到「google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)」
ControlChannel.pb.cc:(.text+0x2f9e): 未定義參考到「google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)」
release/ControlChannel.pb.o: In function `Protocol::Data::Control::protobuf_AddDesc_ControlChannel_2eproto()':
ControlChannel.pb.cc:(.text+0x5e2b): 未定義參考到「google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))」
release/ControlChannel.pb.o: In function `Protocol::Data::Control::protobuf_AssignDesc_ControlChannel_2eproto()':
ControlChannel.pb.cc:(.text+0x61a7): 未定義參考到「google::protobuf::DescriptorPool::FindFileByName(std::string const&) const」
release/AuthHiddenService.pb.o: In function `Protocol::Data::AuthHiddenService::Proof::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
AuthHiddenService.pb.cc:(.text+0x29d): 未定義參考到「google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)」
AuthHiddenService.pb.cc:(.text+0x2b5): 未定義參考到「google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)」
release/AuthHiddenService.pb.o: In function `Protocol::Data::AuthHiddenService::Proof::SerializeWithCachedSizesToArray(unsigned char*) const':
AuthHiddenService.pb.cc:(.text+0x468): 未定義參考到「google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)」
AuthHiddenService.pb.cc:(.text+0x483): 未定義參考到「google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)」
release/AuthHiddenService.pb.o: In function `Protocol::Data::AuthHiddenService::Proof::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)':
AuthHiddenService.pb.cc:(.text+0x8e5): 未定義參考到「google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)」
AuthHiddenService.pb.cc:(.text+0x956): 未定義參考到「google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)」
release/AuthHiddenService.pb.o: In function `Protocol::Data::AuthHiddenService::protobuf_AddDesc_AuthHiddenService_2eproto()':
AuthHiddenService.pb.cc:(.text+0x1f0c): 未定義參考到「google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))」
release/AuthHiddenService.pb.o: In function `Protocol::Data::AuthHiddenService::protobuf_AssignDesc_AuthHiddenService_2eproto()':
AuthHiddenService.pb.cc:(.text+0x20ad): 未定義參考到「google::protobuf::DescriptorPool::FindFileByName(std::string const&) const」
release/ChatChannel.pb.o: In function `Protocol::Data::Chat::ChatMessage::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
ChatChannel.pb.cc:(.text+0x2eb): 未定義參考到「google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)」
release/ChatChannel.pb.o: In function `Protocol::Data::Chat::ChatMessage::SerializeWithCachedSizesToArray(unsigned char*) const':
ChatChannel.pb.cc:(.text+0x7b1): 未定義參考到「google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)」
release/ChatChannel.pb.o: In function `Protocol::Data::Chat::ChatMessage::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)':
ChatChannel.pb.cc:(.text+0xde5): 未定義參考到「google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)」
release/ChatChannel.pb.o: In function `Protocol::Data::Chat::protobuf_AddDesc_ChatChannel_2eproto()':
ChatChannel.pb.cc:(.text+0x1f67): 未定義參考到「google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))」
release/ChatChannel.pb.o: In function `Protocol::Data::Chat::protobuf_AssignDesc_ChatChannel_2eproto()':
ChatChannel.pb.cc:(.text+0x20cd): 未定義參考到「google::protobuf::DescriptorPool::FindFileByName(std::string const&) const」
release/ContactRequestChannel.pb.o: In function `Protocol::Data::ContactRequest::ContactRequest::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
ContactRequestChannel.pb.cc:(.text+0x16b): 未定義參考到「google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)」
ContactRequestChannel.pb.cc:(.text+0x19e): 未定義參考到「google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)」
release/ContactRequestChannel.pb.o: In function `Protocol::Data::ContactRequest::ContactRequest::SerializeWithCachedSizesToArray(unsigned char*) const':
ContactRequestChannel.pb.cc:(.text+0x40b): 未定義參考到「google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)」
ContactRequestChannel.pb.cc:(.text+0x441): 未定義參考到「google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)」
release/ContactRequestChannel.pb.o: In function `Protocol::Data::ContactRequest::ContactRequest::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)':
ContactRequestChannel.pb.cc:(.text+0x5f9): 未定義參考到「google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)」
ContactRequestChannel.pb.cc:(.text+0x686): 未定義參考到「google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)」
release/ContactRequestChannel.pb.o: In function `Protocol::Data::ContactRequest::protobuf_AddDesc_ContactRequestChannel_2eproto()':
ContactRequestChannel.pb.cc:(.text+0x1686): 未定義參考到「google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))」
release/ContactRequestChannel.pb.o: In function `Protocol::Data::ContactRequest::protobuf_AssignDesc_ContactRequestChannel_2eproto()':
ContactRequestChannel.pb.cc:(.text+0x17cd): 未定義參考到「google::protobuf::DescriptorPool::FindFileByName(std::string const&) const」
collect2: error: ld returned 1 exit status
gmake[1]: *** [Makefile.Release:320: ricochet] Error 1
gmake[1]: Leaving directory '/usr/home/lzhou/github.com/ricochet-im/ricochet/archive/ricochet-1.1.4'
gmake: *** [Makefile:38: release] Error 2

**Comment by rburchell** [comment]
Google translate tells me that "未定義參考到" means not defined. I would guess that something doesn't match up with the code generated using protoc vs the protocol buffers code you are linking to.

Check what protoc is being used, and what protobuf lib version.
