### ISSUE TITLE
Version 1.1.4 crashes on NetBSD

### ISSUE THREAD

**Issue by alnsn** [ricochet-im/ricochet#550]
Most of the time, ricochet crashes early:

`==24764==Shadow memory range interleaves with an existing memory mapping. ASan cannot proceed correctly. ABORTING.`

But some times it prints more interesting stuff:

    Correcting permissions on configuration directory
    RNG seed took 0 ms
    void Tor::TorManagerPrivate::processStateChanged(int) 1 3 "w\\Z#d#%Ybu qKkSY" QHostAddress("") 0
    tor: "Aug 02 20:05:21.241 [notice] Tor 0.3.0.10 (git-c33db290a9d8d0f9) running on NetBSD with Libevent 2.1.8-stable, OpenSSL 1.0.2k and Zlib 1.2.10."
    tor: "Aug 02 20:05:21.241 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning"
    tor: "Aug 02 20:05:21.241 [notice] Read configuration file \"/home/alnsn/ricochet-config/./tor/default_torrc\"."
    tor: "Aug 02 20:05:21.241 [notice] Read configuration file \"/home/alnsn/ricochet-config/./tor//torrc\"."
    tor: "Aug 02 20:05:21.242 [warn] Path for ControlPortWriteToFile (./tor//control-port) is relative and will resolve to /home/alnsn/ricochet-config/./tor//control-port. Is this what you wanted?"
    tor: "Aug 02 20:05:21.242 [warn] Path for DataDirectory (./tor/) is relative and will resolve to /home/alnsn/ricochet-config/./tor/. Is this what you wanted?"
    tor: "Aug 02 20:05:21.243 [notice] Opening Control listener on 127.0.0.1:0"
    tor: "Aug 02 20:05:21.243 [notice] Control listener listening on port 64411."
    tor: "Aug 02 20:05:21.243 [notice] DisableNetwork is set. Tor will not make or accept non-control network connections. Shutting down all existing connections."
    tor: "Aug 02 20:05:21.243 [warn] Fixing permissions on directory ./tor/"
    tor: "Aug 02 20:05:21.000 [notice] Parsing GEOIP IPv4 file /usr/pkg/share/tor/geoip."
    tor: "Aug 02 20:05:21.000 [notice] Parsing GEOIP IPv6 file /usr/pkg/share/tor/geoip6."
    tor: "Aug 02 20:05:21.000 [notice] We were built to run on a 64-bit CPU, with OpenSSL 1.0.1 or later, but with a version of OpenSSL that apparently lacks accelerated support for the NIST P-224 and P-256 groups. Building openssl with such support (using the enable-ec_nistp_64_gcc_128 option when configuring it) would make ECDH much faster."
    tor: "Aug 02 20:05:21.000 [notice] Bootstrapped 0%: Starting"
    tor: "Aug 02 20:05:21.000 [notice] Delaying directory fetches: DisableNetwork is set."
    void Tor::TorManagerPrivate::processStateChanged(int) 2 3 "w\\Z#d#%Ybu qKkSY" QHostAddress("") 0
    LLVM ERROR: Program used external function 'llvm.x86.sse41.pminsd' which could not be resolved!
    ASAN:SIGSEGV
    =================================================================
    ==695==ERROR: AddressSanitizer: SEGV on unknown address 0x000058000009 (pc 0x769b186cf383 bp 0x7f7fff86d2b0 sp 0x7f7fff86d1b8 T0)
    #0 0x769b186cf382 in unlink_block (/usr/pkg/lib/dri/swrast_dri.so+0x2cf382)

    AddressSanitizer can not provide additional info.
    SUMMARY: AddressSanitizer: SEGV ??:0 unlink_block
    ==695==ABORTING

**Comment by rburchell** [comment]
Unfortunately, none of us use/know anything about NetBSD, so I think you're more or less on your own. You can set no-hardened during build, which will disable ASAN & others. Sometimes they have caused problems on more esoteric platforms/configurations.
