### ISSUE TITLE
crashed on "ElementaryOS" 

### ISSUE THREAD

**Issue by mhsp2822** [ricochet-im/ricochet#551]
**Crashed on "elementaryOS"**

While connection is 10% it's stop for a while then crash

**Comment by Baccount** [comment]
There has been almost no changes in the code in the last year, so it looks like you should try and look at Tor Messenger Beta to replace it. the version of tor that ricochet uses is Tor 0.2.8.9 ant that is outdated at this point. Here is the link to the official Tor Messenger Beta. remember it is still a beta so there may be possible security issues.

https://trac.torproject.org/projects/tor/wiki/doc/TorMessenger#Downloads
Copied from

**Comment by rburchell** [comment]
If you're using the official binaries, if you can get a backtrace, then please open a bug with that information. If you are using some kind of a distribution package, I would recommend opening a bug with your distribution instead.

Unfortunately, just saying that it crashed isn't of much help as-is, I haven't seen any similar reports elsewhere here.
