### ISSUE TITLE
Is ricochet stopped developing?

### ISSUE THREAD

**Issue by jingjinghack** [ricochet-im/ricochet#553]
last released at 1 year ago...

**Comment by Baccount** [comment]
There has been almost no changes in the code in the last year, so it looks like you should try and look at Tor Messenger Beta to replace it. the version of tor that ricochet uses is Tor 0.2.8.9 ant that is outdated at this point. Here is the link to the official Tor Messenger Beta.

https://trac.torproject.org/projects/tor/wiki/doc/TorMessenger#Downloads

**Comment by cybershambles** [comment]
Have you noticed that ricochet-go has been updated like.. two days ago?

https://github.com/ricochet-im/ricochet-go/commits/master

He's working on the next version... be cool

**Comment by rburchell** [comment]
Yes, development is ongoing.
