### ISSUE TITLE
So many times

### ISSUE THREAD

**Issue by szh7379** [ricochet-im/ricochet#556]
Most of the time people spent on IM is group chat, especially a serverless PC messenger, no server, no offline messages. adding friend, send message, all these are troubles. In a P2P IM, people get less friends than other IM, if you want they keep using it, they must get more messages, they need group feature.Group chat should be the NO.1 feature need be added after basic messaging function.

Had try tox, its group was bad, people need creat it when they log in every time. right, it is p2p, no data be saved in server, but i think an universal value of a group can be created in everyone's drive, when you log in, if the tox can't find it online, then creat it. it can sovle the problem.

So many times, the topic be discussed, but it hadn't been added, seriously group chat should be the NO.1, if you want more people use it. if a tool can't be a porpular one, no more users, then no more development, it will be inactive, i don't think it will be a long time opensource app.

**Comment by rburchell** [comment]
Thanks for your suggestion. Group messaging is already tracked over on #54.

**Comment by scottprovost** [comment]
Building an anonymous gateway for anon chat is trivial and easily done. No reason for such a gateway to be specific to any one chat system. I can demo such a system if you like. No need for Ricochet to write anything special.
