### ISSUE TITLE
Will ricochet support i2p?

### ISSUE THREAD

**Issue by szh7379** [ricochet-im/ricochet#560]
I2p can creat hidden service too,  via SAM or BOB bridge,  just like tor's control port, with api won't need more works. Because in some country connect to tor network is very difficult, but i2p work with KAD, it is diificult to blocked.

If you think i2p can't built-in, you can built-in i2pd, it is recommended by i2p officially. or just procide a opition to control port, no need to built-in i2p.

Really want ricochet be more users used.

**Comment by rburchell** [comment]
See #82.

**Comment by szh7379** [comment]
Ok, i got it, will be a very long time to think about it, it is real very hard to connect to tor in my country, so i really want devs consider that.
