### ISSUE TITLE
Installation error on OSX (High Sierra)

### ISSUE THREAD

**Issue by d3prof3t** [ricochet-im/ricochet#561]
I'm facing an issue with the installation process. Please refer to the link for screenshot of the same [here](https://share.riseup.net/#5_OBselnFc6cOdfB97ee4w
)

**Comment by d3prof3t** [comment]
I've found a solution to this using `brew cask`. If anybody requires then refer [here](http://macappstore.org/ricochet/) for instructions.

**Comment by rburchell** [comment]
glad you found a workaround. the issue itself is a duplicate of #122.

in future, please upload things to Github directly or transcribe them (drag and drop, or clipboard) - having the content directly in the issue tracker is a lot more future-proof.
