### ISSUE TITLE
Project dead ?

### ISSUE THREAD

**Issue by Betaman2k** [ricochet-im/ricochet#568]
Heya
last update 1+ year
no furure for this software or NSA buy the software hehe

**Comment by Betaman2k** [comment]
Heya
last update 1+ year
no furure for this software or NSA buy the software hehe

**Comment by burdges** [comment]
Biar is a roughly equivalent project with on-going development.

**Comment by s-rah** [comment]
Please see my response to #555 : https://github.com/ricochet-im/ricochet/issues/555#issuecomment-324094653

While it's true the main client hasn't seen many updates, there is plenty of on going development happening projects related to ricochet.

**Comment by ghost** [comment]
I think Pascal (and Object Pascal) is more easy than go (in all) and there is an IM software called torchat in which latest versions are based on him (Pascal and Object Pascal).

**Comment by ei8fdb** [comment]
@s-rah you mentioned in #555 about the need for UX input. If that was available, what are the post pressing needs?

**Comment by ghost** [comment]
@burdges can you please share a link to Biar? I can't find it through searching.

**Comment by burdges** [comment]
https://briarproject.org/

**Comment by ghost** [comment]
It is not for desktop devices.

**Comment by ghost** [comment]
Thanks. Any other analogous projects but for desktop?
I know there is an OTR plugin for pidgin (but pidgin doesn't use Tor).

**Comment by ghost** [comment]
TorChat but it was also abandoned. First, it was written in Python, later, in Pascal.

**Comment by ghost** [comment]
Pascal version it is only supported by pidgin.

**Comment by ghost** [comment]
When you say "also" that implies the current one is abandoned too?

**Comment by ghost** [comment]
I think this but i didn't want to put it. I am not sure, really.
