### ISSUE TITLE
You have plans in feature making this messanger for android ?

### ISSUE THREAD

**Issue by Kratumn** [ricochet-im/ricochet#570]
i love this messanger is the best idea , i want to use this on my android device

**Comment by s-rah** [comment]
See #115 

There is some work being done outside this project e.g. https://github.com/dballard/goRicochetMobile

**Comment by Kratumn** [comment]
Nice

**Comment by bitnom** [comment]
It's gone :( I was thinking about it today and perhaps a Nim wrapper could be a relatively straight-forward path to Android.

**Comment by cypherbits** [comment]
@TensorTom Ricochet.im project is gone.

The "new" project that wanted to resurrect it (https://ricochetrefresh.net/) is gone too... I said this would happen to them...

If we need something like Ricochet: contribute to Cwtch.im their developers are active (slow, but active) and some were Tor developers in the past.

**Comment by s-rah** [comment]
The work that was done by Dan on Ricochet Mobile, eventually worked it's way into Cwtch and we have a fairly stable Android client now: https://openprivacy.ca/blog/2019/12/17/cwtch-alpha-0.3.1/

Not only does it support ricochet-style (2 peer ephemeral messaging), it also supports groups using untrusted infrastructure.

Still a long way to go, but we are making steady progress.

**Comment by bitnom** [comment]
> The work that was done by Dan on Ricochet Mobile, eventually worked it's way into Cwtch and we have a fairly stable Android client now: https://openprivacy.ca/blog/2019/12/17/cwtch-alpha-0.3.1/
> 
> Not only does it support ricochet-style (2 peer ephemeral messaging), it also supports groups using untrusted infrastructure.
> 
> Still a long way to go, but we are making steady progress.

https://git.openprivacy.ca/user/sign_up

Registration is disabled. Cannot use `go get` or `git clone`

**Comment by s-rah** [comment]
Our git repositories were the subject of a DoS attack yesterday: https://twitter.com/OpenPriv/status/1237140260955369472 and locked down our gitea instance to registered users to minimize disruption to our staff and volunteers, we have since reenabled our gitea instance and it should be accessible to anonymous users again.
