### ISSUE TITLE
it is DEAD ?

### ISSUE THREAD

**Issue by burkifaso** [ricochet-im/ricochet#574]
this project is DEAD ? im pretty sure it is...no update .. nothing

**Comment by s-rah** [comment]
Nope not dead, just resting. Lot's of work going on in auxiliary projects, like the go library: https://github.com/s-rah/go-ricochet

See also: #568

**Comment by s-rah** [comment]
And https://github.com/ricochet-im/ricochet/issues/555#issuecomment-324094653 for a more detailed answer.

**Comment by burkifaso** [comment]
why no new windows, linux , mac releases compiled..and ready for download... ??

**Comment by WPFilmmaker** [comment]
@s-rah Would you be able to estimate when normal users will be able to benefits from the ongoing developments of such ricochet auxiliary projects? Are you planning on releasing a go-written ricochet messenger as alternative to this one? Thanks for your work!

**Comment by ApostolosB** [comment]
@s-rah if you could add a news/what are we up to section on the website with updates every month or two would also help.
