### ISSUE TITLE
Tor Wiki and User Perceptions

### ISSUE THREAD

**Issue by ghost** [ricochet-im/ricochet#581]
https://trac.torproject.org/projects/tor/wiki/doc/TorifyHOWTO/InstantMessaging

Software listed here has become depreciated and development has ceased. They are therefore considered unsafe and it is highly recommended to avoid using them. This section is here purely for historical value.

Ricochet IM is an open-source, decentralised instant messenger project that officially ended development in November 2016. Ricochet starts a Tor onion service on the users local system and facilitates communication with other Ricochet users whom are also running their own Ricochet-created Tor onion service, providing End-to-End encryption by never allowing the connection to leave the Tor network.

**Comment by ghost** [comment]
@Betaman2k @burkifaso Collaborator s-rah is too ignorant to close "dead?" question threads LOL

**Comment by ghost** [comment]
## Software listed here has become depreciated and development has ceased.
## They are therefore considered unsafe and it is highly recommended to avoid using them.

 ## Ricochet

**Comment by s-rah** [comment]
The Tor wiki reflects the opinions of the Tor Project, and does not represent an official statement about the status of Ricochet.

Please stop creating duplicate issues and pull requests, especially those which attempt to pass themselves off as official statement on the status of this Ricochet project. I have kept #580 open and any further discussion over messaging to send to users regarding the status of the project can take place there.

https://github.com/ricochet-im/ricochet/issues/578#issuecomment-393049811
