### ISSUE TITLE
website certificate expired

### ISSUE THREAD

**Issue by jeroenev** [ricochet-im/ricochet#591]

**Comment by ThatLurker** [comment]
seems ok to me 
<img width="347" alt="screenshot 33" src="https://user-images.githubusercontent.com/1533244/48650621-accf5000-e9ff-11e8-938c-2284573c2d69.png">

**Comment by jeroenev** [comment]
Yeah it's OK now, 
It was expired when i posted this

**Comment by 4urb4nm0nk** [comment]
I'ts occuring again, expired on 12/6
https://imgur.com/gqeuTPR

**Comment by jeroenev** [comment]
and it's fixed again
