### ISSUE TITLE
Dead keys and other input methods don't work with linux static builds

### ISSUE THREAD

**Issue by obvio171** [ricochet-im/ricochet#60]
Must be an issue with Qt, but can't type characters like 'á', 'ã', 'ç', etc.

**Comment by special** [comment]
@rburchell points out that we should make sure the `src/plugins/platforminputcontexts/compose` Qt plugin is built in. Adding something to `QTPLUGIN` in the .pro file might help here.

**Comment by special** [comment]
That hint was correct, but we ideally want ibus too. To compile those plugins into the linux-static build, ricochet.pro needs to contain:

```
QTPLUGIN.platforminputcontexts = composeplatforminputcontextplugin ibusplatforminputcontextplugin
```

The ibus plugin requires qtdbus, but this already seems to be available in the build-time environment and isn't creating any additional runtime dependencies.

Using only compose would probably only partially solve the problem, and some desktops (e.g. Gnome) set `QT_IM_MODULE=ibus` in the environment, which breaks if we only have compose.
