### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by pdarcos** [ricochet-im/ricochet#604]
Hi,

I don't see any commits here for a number of years and I only see the master branch.

Is this project dead or has it been forked and replaced somewhere?

It's a great project IMHO but sadly it seems to be stalled since 2017.

Cheers

**Comment by cypherbits** [comment]
> Hi,
> 
> I don't see any commits here for a number of years and I only see the master branch.
> 
> Is this project dead or has it been forked and replaced somewhere?
> 
> It's a great project IMHO but sadly it seems to be stalled since 2017.
> 
> Cheers

No, the new is cwitch.im

**Comment by pdarcos** [comment]
Thanks! cwitch looks promising
