### ISSUE TITLE
Public ricochet ID location

### ISSUE THREAD

**Issue by matt1tk** [ricochet-im/ricochet#605]
Where is the public ricochet ID stored?

**Comment by cypherbits** [comment]
What do you mean about that?

**Comment by matt1tk** [comment]
Just wondering in what file the public ricochet ID is stored. The private one is located in the config, but if I wanted to let ricochet run and access the public ID automatically, how would I do it?

**Comment by s-rah** [comment]
Ricochet derives the public key from the private key at runtime: https://github.com/ricochet-im/ricochet/blob/a22c729b3e912794a8af65879ed1b38573385657/src/protocol/AuthHiddenServiceChannel.cpp#L196

**Comment by matt1tk** [comment]
Thanks!
