### ISSUE TITLE
Ricochet for iPhone ?

### ISSUE THREAD

**Issue by ghost** [ricochet-im/ricochet#608]
Ricochet for iPhone ?

**Comment by odiferousmint** [comment]
Well, there's iOS support for Qt, so it is probably possible. I do not think anyone is working on Ricochet anymore. It still needs to support Onion v3 hidden services. It is not that difficult to add support for that, but I currently lack the time. It is on my list of things to do in the future.

**Comment by Khautz** [comment]
Thank you for your answer

**Comment by ghost** [comment]
Thank you for your answer

**Comment by cypherbits** [comment]
Guys, Ricochet is dead. No work on desktop, less on porting to iOS...
