### ISSUE TITLE
Incoming contact request while contact dialog is open freezes UI

### ISSUE THREAD

**Issue by special** [ricochet-im/ricochet#74]
Applies to OS X and some Linux systems (gnome 2?):
1. Open "Add Contact" dialog
2. Share address with Bob, leaving the contact dialog open
3. Receive a contact request from Bob

The incoming contact request tries to open a second modal window, and some systems freak out at this. It can result in the entire program being impossible to interact with, or even breaking the window system.

**Comment by kolodziej** [comment]
I have found that removing parent object when creating dialog helps in my case (I use KDE 4.14.2 on Debian Jessie).
