### ISSUE TITLE
As a replacement for Invisible.im, will you also be supporting I2P as they were planning to?

### ISSUE THREAD

**Issue by rodneyrod** [ricochet-im/ricochet#82]
Having an anonymous chat service that spans multiple networks hasn't been accomplished yet, and would give Ricochet greater legitimacy in those areas.

**Comment by hkparker** [comment]
A good write-up about the basics of i2p development is available [here](https://geti2p.net/en/get-involved/develop/applications).  They advertise being optimized for hidden services which could be advantageous, but I'm less familiar with i2p as well.

**Comment by rodneyrod** [comment]
How come this was closed?

**Comment by special** [comment]
@rodneyrod There are no plans to support i2p in Ricochet, even in the long term. I think it's outside of the project's scope as it stands now.

That doesn't mean it won't ever happen, but we'll need to make some big decisions about the direction of the project before it could.
