### ISSUE TITLE
Chat Stealth Mode: HS Authentcation

### ISSUE THREAD

**Issue by HulaHoopWhonix** [ricochet-im/ricochet#87]
I think that there is a benefit in providing users with the option to communicate in "Stealth Mode" by making use of the Hidden Service Authentication, a less known feature that completely blocks connections to a HS from everybody but a group of intended users.

I have suggested this to onionshare as well here. Please read it for more details:
https://github.com/micahflee/onionshare/issues/144

**Comment by special** [comment]
See #155
