### ISSUE TITLE
Ricochet 1.0.4 not working on Windows XP SP3

### ISSUE THREAD

**Issue by botherder** [ricochet-im/ricochet#91]
The distributed Ricochet 1.0.4 does not correctly support Windows XP. The process subsystem believes the final client executable is malformed and raises a ERROR_BAD_EXE_FORMAT (code 193).
I tested and verified this only on Windows XP SP3 32bit, while it does work fine on more recent versions of Windows (7 and 8).

**Comment by special** [comment]
Someone should try this again with the 1.1.0 release. The Windows builds are now done with MinGW, so it might cause a different set of problems.

I've heard rumors that the dynamic opengl build we use won't work on Windows XP, so there might still be issues.

**Comment by gabedwrds** [comment]
1.1.0 works for me using the "IE6 on Windows XP, Build 20141027 for Mac" VM from [modern.ie](https://www.modern.ie/en-us/virtualization-tools)
